# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - doxygen
    - graphviz
  commands:
    # 1) Install Python requirements for Sphinx & extensions
    - echo "Installing Python dependencies…"
    - python -m pip install -r docs/requirements.txt

    # 2) Generate Doxygen XML (Makefile’s doxygen target)
    - echo "Generating Doxygen XML…"
    - make doxygen

    # 3) Build full HTML (Makefile’s html target runs sphinx-build)
    - echo "Building Sphinx docs…"
    - make html

    # 4) Copy the output into RTD’s expected dir
    - echo "Copying HTML to RTD output…"
    - cp -R docs/_build/html "$READTHEDOCS_OUTPUT/html"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
