# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8" # Or a newer version compatible with your docs/requirements.txt
  apt_packages:
    - doxygen
    - graphviz
  commands:
    - echo "--- Environment Info ---"
    - pwd
    - 'echo "Current PATH: $PATH"'
    - echo "Listing root directory:"
    - ls -la
    - echo "Listing docs directory:"
    - ls -la docs
    - echo "--- Initial Tool Versions & Locations ---"
    - python --version
    - pip --version
    - which python
    - which pip
    - echo "--- Attempting to install packages from docs/requirements.txt manually ---"
    - python -m pip install -r docs/requirements.txt
    - echo "--- Tool Versions After Manual Pip Install ---"
    - python --version
    - pip --version
    - doxygen --version
    - sphinx-build --version || echo "sphinx-build still not found after manual install"
    - which sphinx-build || echo "sphinx-build location not found"
    - echo "--- Running Doxygen ---"
    - echo "Contents of project root src/ (for reference):"
    - ls -la src/
    - echo "Contents of project root docs/ (for reference):"
    - ls -la docs/
    # Run Doxygen from the project root, where Doxyfile is located
    # Output Doxygen log to project root for easier access in RTD build artifacts.
    - doxygen Doxyfile > doxygen_run.log 2>&1
    - echo "Doxygen command finished. Log content (from project root):"
    - cat doxygen_run.log
    - 'echo "--- Listing Doxygen Output Directory (expected: doxygen/) ---"'
    - ls -lR doxygen/ || echo "doxygen/ not found or listing failed."
    - 'echo "--- Listing Doxygen XML Output Directory (expected: doxygen/xml/) ---"'
    - ls -lR doxygen/xml/ || echo "doxygen/xml/ not found or listing failed."
    - echo "--- Running Sphinx ---"
    # -W: Treat warnings as errors (suppress_warnings in conf.py should be respected)
    # -E: Always rebuild environment
    # -v: Verbosity
    # Source directory: docs (relative to project root)
    # Output directory: $READTHEDOCS_OUTPUT/html (where RTD expects it)
    - sphinx-build -W -E -v -b html docs "$READTHEDOCS_OUTPUT/html"

# Python configuration for installing dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration (used by RTD to understand the project)
sphinx:
  configuration: docs/conf.py

