# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/philip/Github/Software/OCTypes-SITypes/SITypes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/philip/Github/Software/OCTypes-SITypes/SITypes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philip/Github/Software/OCTypes-SITypes/SITypes/CMakeFiles /Users/philip/Github/Software/OCTypes-SITypes/SITypes//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philip/Github/Software/OCTypes-SITypes/SITypes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SITypes

# Build rule for target.
SITypes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SITypes
.PHONY : SITypes

# fast build rule for target.
SITypes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/build
.PHONY : SITypes/fast

SIDimensionalityParser.tab.o: SIDimensionalityParser.tab.c.o
.PHONY : SIDimensionalityParser.tab.o

# target to build an object file
SIDimensionalityParser.tab.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIDimensionalityParser.tab.c.o
.PHONY : SIDimensionalityParser.tab.c.o

SIDimensionalityParser.tab.i: SIDimensionalityParser.tab.c.i
.PHONY : SIDimensionalityParser.tab.i

# target to preprocess a source file
SIDimensionalityParser.tab.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIDimensionalityParser.tab.c.i
.PHONY : SIDimensionalityParser.tab.c.i

SIDimensionalityParser.tab.s: SIDimensionalityParser.tab.c.s
.PHONY : SIDimensionalityParser.tab.s

# target to generate assembly for a file
SIDimensionalityParser.tab.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIDimensionalityParser.tab.c.s
.PHONY : SIDimensionalityParser.tab.c.s

SIScanner.o: SIScanner.c.o
.PHONY : SIScanner.o

# target to build an object file
SIScanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIScanner.c.o
.PHONY : SIScanner.c.o

SIScanner.i: SIScanner.c.i
.PHONY : SIScanner.i

# target to preprocess a source file
SIScanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIScanner.c.i
.PHONY : SIScanner.c.i

SIScanner.s: SIScanner.c.s
.PHONY : SIScanner.s

# target to generate assembly for a file
SIScanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/SIScanner.c.s
.PHONY : SIScanner.c.s

src/SIDimensionality.o: src/SIDimensionality.c.o
.PHONY : src/SIDimensionality.o

# target to build an object file
src/SIDimensionality.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIDimensionality.c.o
.PHONY : src/SIDimensionality.c.o

src/SIDimensionality.i: src/SIDimensionality.c.i
.PHONY : src/SIDimensionality.i

# target to preprocess a source file
src/SIDimensionality.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIDimensionality.c.i
.PHONY : src/SIDimensionality.c.i

src/SIDimensionality.s: src/SIDimensionality.c.s
.PHONY : src/SIDimensionality.s

# target to generate assembly for a file
src/SIDimensionality.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIDimensionality.c.s
.PHONY : src/SIDimensionality.c.s

src/SIQuantity.o: src/SIQuantity.c.o
.PHONY : src/SIQuantity.o

# target to build an object file
src/SIQuantity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIQuantity.c.o
.PHONY : src/SIQuantity.c.o

src/SIQuantity.i: src/SIQuantity.c.i
.PHONY : src/SIQuantity.i

# target to preprocess a source file
src/SIQuantity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIQuantity.c.i
.PHONY : src/SIQuantity.c.i

src/SIQuantity.s: src/SIQuantity.c.s
.PHONY : src/SIQuantity.s

# target to generate assembly for a file
src/SIQuantity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIQuantity.c.s
.PHONY : src/SIQuantity.c.s

src/SIScalar.o: src/SIScalar.c.o
.PHONY : src/SIScalar.o

# target to build an object file
src/SIScalar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalar.c.o
.PHONY : src/SIScalar.c.o

src/SIScalar.i: src/SIScalar.c.i
.PHONY : src/SIScalar.i

# target to preprocess a source file
src/SIScalar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalar.c.i
.PHONY : src/SIScalar.c.i

src/SIScalar.s: src/SIScalar.c.s
.PHONY : src/SIScalar.s

# target to generate assembly for a file
src/SIScalar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalar.c.s
.PHONY : src/SIScalar.c.s

src/SIScalarConstants.o: src/SIScalarConstants.c.o
.PHONY : src/SIScalarConstants.o

# target to build an object file
src/SIScalarConstants.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarConstants.c.o
.PHONY : src/SIScalarConstants.c.o

src/SIScalarConstants.i: src/SIScalarConstants.c.i
.PHONY : src/SIScalarConstants.i

# target to preprocess a source file
src/SIScalarConstants.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarConstants.c.i
.PHONY : src/SIScalarConstants.c.i

src/SIScalarConstants.s: src/SIScalarConstants.c.s
.PHONY : src/SIScalarConstants.s

# target to generate assembly for a file
src/SIScalarConstants.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarConstants.c.s
.PHONY : src/SIScalarConstants.c.s

src/SIScalarParser.o: src/SIScalarParser.c.o
.PHONY : src/SIScalarParser.o

# target to build an object file
src/SIScalarParser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParser.c.o
.PHONY : src/SIScalarParser.c.o

src/SIScalarParser.i: src/SIScalarParser.c.i
.PHONY : src/SIScalarParser.i

# target to preprocess a source file
src/SIScalarParser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParser.c.i
.PHONY : src/SIScalarParser.c.i

src/SIScalarParser.s: src/SIScalarParser.c.s
.PHONY : src/SIScalarParser.s

# target to generate assembly for a file
src/SIScalarParser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParser.c.s
.PHONY : src/SIScalarParser.c.s

src/SIScalarParserHelpers.o: src/SIScalarParserHelpers.c.o
.PHONY : src/SIScalarParserHelpers.o

# target to build an object file
src/SIScalarParserHelpers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParserHelpers.c.o
.PHONY : src/SIScalarParserHelpers.c.o

src/SIScalarParserHelpers.i: src/SIScalarParserHelpers.c.i
.PHONY : src/SIScalarParserHelpers.i

# target to preprocess a source file
src/SIScalarParserHelpers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParserHelpers.c.i
.PHONY : src/SIScalarParserHelpers.c.i

src/SIScalarParserHelpers.s: src/SIScalarParserHelpers.c.s
.PHONY : src/SIScalarParserHelpers.s

# target to generate assembly for a file
src/SIScalarParserHelpers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIScalarParserHelpers.c.s
.PHONY : src/SIScalarParserHelpers.c.s

src/SIUnit.o: src/SIUnit.c.o
.PHONY : src/SIUnit.o

# target to build an object file
src/SIUnit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIUnit.c.o
.PHONY : src/SIUnit.c.o

src/SIUnit.i: src/SIUnit.c.i
.PHONY : src/SIUnit.i

# target to preprocess a source file
src/SIUnit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIUnit.c.i
.PHONY : src/SIUnit.c.i

src/SIUnit.s: src/SIUnit.c.s
.PHONY : src/SIUnit.s

# target to generate assembly for a file
src/SIUnit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SITypes.dir/build.make CMakeFiles/SITypes.dir/src/SIUnit.c.s
.PHONY : src/SIUnit.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SITypes"
	@echo "... SIDimensionalityParser.tab.o"
	@echo "... SIDimensionalityParser.tab.i"
	@echo "... SIDimensionalityParser.tab.s"
	@echo "... SIScanner.o"
	@echo "... SIScanner.i"
	@echo "... SIScanner.s"
	@echo "... src/SIDimensionality.o"
	@echo "... src/SIDimensionality.i"
	@echo "... src/SIDimensionality.s"
	@echo "... src/SIQuantity.o"
	@echo "... src/SIQuantity.i"
	@echo "... src/SIQuantity.s"
	@echo "... src/SIScalar.o"
	@echo "... src/SIScalar.i"
	@echo "... src/SIScalar.s"
	@echo "... src/SIScalarConstants.o"
	@echo "... src/SIScalarConstants.i"
	@echo "... src/SIScalarConstants.s"
	@echo "... src/SIScalarParser.o"
	@echo "... src/SIScalarParser.i"
	@echo "... src/SIScalarParser.s"
	@echo "... src/SIScalarParserHelpers.o"
	@echo "... src/SIScalarParserHelpers.i"
	@echo "... src/SIScalarParserHelpers.s"
	@echo "... src/SIUnit.o"
	@echo "... src/SIUnit.i"
	@echo "... src/SIUnit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

