#line 1 "src/SIScalarScanner.c"

#line 3 "src/SIScalarScanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer sis_create_buffer
#define yy_delete_buffer sis_delete_buffer
#define yy_scan_buffer sis_scan_buffer
#define yy_scan_string sis_scan_string
#define yy_scan_bytes sis_scan_bytes
#define yy_init_buffer sis_init_buffer
#define yy_flush_buffer sis_flush_buffer
#define yy_load_buffer_state sis_load_buffer_state
#define yy_switch_to_buffer sis_switch_to_buffer
#define yypush_buffer_state sispush_buffer_state
#define yypop_buffer_state sispop_buffer_state
#define yyensure_buffer_stack sisensure_buffer_stack
#define yy_flex_debug sis_flex_debug
#define yyin sisin
#define yyleng sisleng
#define yylex sislex
#define yylineno sislineno
#define yyout sisout
#define yyrestart sisrestart
#define yytext sistext
#define yywrap siswrap
#define yyalloc sisalloc
#define yyrealloc sisrealloc
#define yyfree sisfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define sis_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer sis_create_buffer
#endif

#ifdef yy_delete_buffer
#define sis_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer sis_delete_buffer
#endif

#ifdef yy_scan_buffer
#define sis_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer sis_scan_buffer
#endif

#ifdef yy_scan_string
#define sis_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string sis_scan_string
#endif

#ifdef yy_scan_bytes
#define sis_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes sis_scan_bytes
#endif

#ifdef yy_init_buffer
#define sis_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer sis_init_buffer
#endif

#ifdef yy_flush_buffer
#define sis_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer sis_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define sis_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state sis_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define sis_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer sis_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define sispush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state sispush_buffer_state
#endif

#ifdef yypop_buffer_state
#define sispop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state sispop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define sisensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack sisensure_buffer_stack
#endif

#ifdef yylex
#define sislex_ALREADY_DEFINED
#else
#define yylex sislex
#endif

#ifdef yyrestart
#define sisrestart_ALREADY_DEFINED
#else
#define yyrestart sisrestart
#endif

#ifdef yylex_init
#define sislex_init_ALREADY_DEFINED
#else
#define yylex_init sislex_init
#endif

#ifdef yylex_init_extra
#define sislex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra sislex_init_extra
#endif

#ifdef yylex_destroy
#define sislex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy sislex_destroy
#endif

#ifdef yyget_debug
#define sisget_debug_ALREADY_DEFINED
#else
#define yyget_debug sisget_debug
#endif

#ifdef yyset_debug
#define sisset_debug_ALREADY_DEFINED
#else
#define yyset_debug sisset_debug
#endif

#ifdef yyget_extra
#define sisget_extra_ALREADY_DEFINED
#else
#define yyget_extra sisget_extra
#endif

#ifdef yyset_extra
#define sisset_extra_ALREADY_DEFINED
#else
#define yyset_extra sisset_extra
#endif

#ifdef yyget_in
#define sisget_in_ALREADY_DEFINED
#else
#define yyget_in sisget_in
#endif

#ifdef yyset_in
#define sisset_in_ALREADY_DEFINED
#else
#define yyset_in sisset_in
#endif

#ifdef yyget_out
#define sisget_out_ALREADY_DEFINED
#else
#define yyget_out sisget_out
#endif

#ifdef yyset_out
#define sisset_out_ALREADY_DEFINED
#else
#define yyset_out sisset_out
#endif

#ifdef yyget_leng
#define sisget_leng_ALREADY_DEFINED
#else
#define yyget_leng sisget_leng
#endif

#ifdef yyget_text
#define sisget_text_ALREADY_DEFINED
#else
#define yyget_text sisget_text
#endif

#ifdef yyget_lineno
#define sisget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno sisget_lineno
#endif

#ifdef yyset_lineno
#define sisset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno sisset_lineno
#endif

#ifdef yywrap
#define siswrap_ALREADY_DEFINED
#else
#define yywrap siswrap
#endif

#ifdef yyalloc
#define sisalloc_ALREADY_DEFINED
#else
#define yyalloc sisalloc
#endif

#ifdef yyrealloc
#define sisrealloc_ALREADY_DEFINED
#else
#define yyrealloc sisrealloc
#endif

#ifdef yyfree
#define sisfree_ALREADY_DEFINED
#else
#define yyfree sisfree
#endif

#ifdef yytext
#define sistext_ALREADY_DEFINED
#else
#define yytext sistext
#endif

#ifdef yyleng
#define sisleng_ALREADY_DEFINED
#else
#define yyleng sisleng
#endif

#ifdef yyin
#define sisin_ALREADY_DEFINED
#else
#define yyin sisin
#endif

#ifdef yyout
#define sisout_ALREADY_DEFINED
#else
#define yyout sisout
#endif

#ifdef yy_flex_debug
#define sis_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug sis_flex_debug
#endif

#ifdef yylineno
#define sislineno_ALREADY_DEFINED
#else
#define yylineno sislineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define siswrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[677] =
    {   0,
       66,   64,   65,   63,   64,   65,   65,   50,   64,   65,
    16436,16437,   64,   65,    7,   64,   65,    8,   64,   65,
        3,   64,   65,    1,   64,   65,    2,   64,   65,   64,
       65,    4,   64,   65,   45,   64,   65,16435,   49,   64,
       65,   50,   64,   65,16436,16437,   64,   65,    5,   64,
       65,   50,   64,   65,16436,16437,   50,   64,   65,16436,
    16437,   50,   64,   65,16436,16437,   50,   64,   65,16436,
    16437,   50,   64,   65,16436,16437,   50,   64,   65,16436,
    16437,   50,   64,   65,16436,16437,   50,   64,   65,16436,
    16437,   50,   64,   65,16436,16437,   50,   64,   65,16436,

    16437,    6,   64,   65,   50,   64,   65,16436,16437,   50,
       64,   65,16436,16437,   64,   65,   59,   65,   65,   65,
       59,   65,   63,16436,16437,   50,   62,16436,16437,   50,
     8244,16436,16437, 8244,   50,   62,16436,16437,   50,16436,
    16437,   50,16436,16437,   61,   45,16435,16435, 8243,   45,
    16435,   45,16435, 8243, 8243,   50,   62,16436,16437,   50,
       62,16436,16437,   50,   62,16436,16437,   50,   62,16436,
    16437,   50,   62,16436,16437,   35,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   50,   62,
    16436,16437,   50,   62,16436,16437,   50,   62,16436,16437,

       50,   62,16436,16437,   50,   62,16436,16437,   36,   50,
       62,16436,16437,   24,   50,   62,16436,16437,   50,   62,
    16436,16437,   50,   62,16436,16437,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   50,   62,
    16436,16437,   50,   62,16436,16437,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   50,   62,
    16436,16437,   59,   59,   59,   59,   50, 8244,   62,16436,
    16437,   62, 8244,16436,16437,   62, 8244,   62,   62, 8244,
       50,16436,16437,   50,   62,16436,16437,   50,   62,16436,
    16437,   61, 8243, 8243,   47,16439,16440,   46,16438,   45,

    16435, 8243,   45, 8243,16435,   45,16435,   48,16441,16442,
       40,   60,   50,   62,16436,16437,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   50,   62,
    16436,16437,   50,   62,16436,16437,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   15,   50,
       62,16436,16437,   50,   62,16436,16437,   21,   50,   62,
    16436,16437,   23,   50,   62,16436,16437,   25,   50,   62,
    16436,16437,   41,   50,   62,16436,16437,   50,   62,16436,
    16437,   50,   62,16436,16437,   17,   50,   62,16436,16437,
       50,   62,16436,16437,   50,   62,16436,16437,   50,   62,

    16436,16437,   19,   50,   62,16436,16437,   50,   62,16436,
    16437,   59,   50,   62,16436,16437,   62, 8245, 8244, 8244,
       62, 8244, 8244,   50, 8244,16436,16437, 8244,   62,   50,
       62,16436,16437, 8243,   47,16439,16440, 8247, 8248, 8247,
     8248,   46,16438, 8246, 8246,   45, 8243,16435,   45,16435,
       48,16441,16442,16441,16442, 8249, 8250,   48,16441,16442,
     8249, 8250, 8249, 8250,   50,   62,16436,16437,    9,   50,
       62,16436,16437,   11,   50,   62,16436,16437,   13,   50,
       62,16436,16437,   30,   50,   62,16436,16437,   29,   50,
       62,16436,16437,   32,   50,   62,16436,16437,   50,   62,

    16436,16437,   26,   50,   62,16436,16437,   16,   50,   62,
    16436,16437,   50,   62,16436,16437,   22,   50,   62,16436,
    16437,   33,   50,   62,16436,16437,   50,   62,16436,16437,
       18,   50,   62,16436,16437,   42,   50,   62,16436,16437,
       31,   50,   62,16436,16437,   43,   20,   50,   62,16436,
    16437,   62,   39,   50, 8244,   62,16436,16437, 8245, 8244,
       50,16436,16437,   44,   50,   62,16436,16437,   50,16436,
    16437, 8247, 8248, 8247, 8248, 8246, 8246, 8249, 8250, 8249,
     8250,   48,16441,16442, 8249, 8250,   48, 8249, 8250,16441,
    16442,   48,16441,16442,   50,   62,16436,16437,   10,   50,

       62,16436,16437,   12,   50,   62,16436,16437,   14,   50,
       62,16436,16437,   28,   50,   62,16436,16437,   27,   50,
       62,16436,16437,   50,   62,16436,16437,   59,   50,   62,
    16436,16437, 8244, 8243, 8247, 8248, 8246, 8249, 8250,   48,
     8249, 8250,16441,16442,   48,16441,16442,   50,   62,16436,
    16437,   34,   50,   62,16436,16437,   62,   38,   50,   62,
    16436,16437, 8247, 8248, 8246, 8249, 8250,   50,   62,16436,
    16437,   37,   50,   62,16436,16437
    } ;

static const flex_int16_t yy_accept[376] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    8,   13,
       15,   18,   21,   24,   27,   30,   32,   35,   39,   42,
       47,   49,   52,   57,   62,   67,   72,   77,   82,   87,
       92,   97,  102,  105,  110,  115,  117,  119,  120,  121,
      123,  124,  126,  130,  130,  130,  130,  134,  135,  135,
      139,  142,  145,  145,  145,  146,  148,  149,  150,  150,
      150,  150,  150,  152,  154,  155,  156,  156,  156,  160,
      160,  164,  168,  172,  176,  181,  185,  189,  193,  197,
      201,  205,  209,  214,  219,  223,  227,  231,  235,  239,
      243,  247,  251,  255,  259,  263,  263,  264,  265,  265,

      266,  267,  267,  272,  272,  273,  273,  274,  276,  277,
      277,  278,  279,  280,  280,  281,  281,  281,  281,  284,
      288,  292,  292,  293,  294,  294,  295,  295,  295,  298,
      298,  298,  298,  300,  302,  303,  303,  306,  308,  308,
      308,  311,  312,  312,  312,  313,  317,  321,  325,  329,
      333,  337,  341,  345,  349,  354,  358,  363,  368,  373,
      378,  382,  386,  391,  395,  399,  403,  408,  408,  412,
      412,  412,  412,  413,  413,  413,  413,  417,  417,  418,
      418,  418,  418,  419,  420,  420,  420,  422,  423,  424,
      424,  424,  428,  430,  434,  434,  434,  434,  435,  435,

      438,  440,  440,  440,  442,  442,  442,  442,  442,  442,
      444,  445,  445,  445,  446,  446,  449,  451,  454,  456,
      458,  458,  458,  461,  463,  465,  465,  469,  474,  479,
      484,  489,  494,  499,  503,  508,  513,  517,  522,  527,
      531,  536,  541,  546,  547,  552,  552,  552,  553,  554,
      554,  554,  554,  554,  554,  554,  559,  559,  559,  559,
      559,  559,  559,  560,  560,  560,  561,  564,  569,  572,
      572,  572,  572,  572,  574,  574,  576,  576,  576,  576,
      576,  576,  576,  577,  577,  578,  578,  580,  580,  582,
      582,  585,  587,  587,  592,  595,  599,  604,  609,  614,

      619,  624,  628,  628,  628,  628,  629,  629,  633,  633,
      633,  633,  633,  633,  633,  633,  634,  634,  634,  635,
      635,  635,  635,  637,  637,  637,  637,  637,  637,  638,
      638,  638,  638,  640,  640,  640,  645,  648,  652,  657,
      658,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  663,
      665,  665,  666,  666,  668,  668,  672,  672,  672,  672,
      672,  672,  672,  677,  677
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,    1,    1,    1,
        1,    1,    1,    1,   17,   17,   17,   17,   18,   17,
       17,   17,   19,   17,   17,   17,   17,   17,   17,   17,
       20,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       21,    1,   22,   23,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,   17,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   17,   45,   46,
       17,   17,    1,   47,    1,    1,    1,    5,    1,    1,
        5,    5,    5,    1,    1,   48,    1,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   49,    1,   50,   48,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    5,   48,    1,    1,    1,
       51,    1,    1,    1,    1,    1,   48,    1,   52,   53,
        1,    1,    1,   54,    5,    1,    1,   48,    1,    1,

        1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   55,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    1,    2,    3,    2,    4,    5,    6,    7,
        7,    8,    1,    9,   10,   10,   11,   11,    5,   11,
        1,   12,   13,    3,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    1,   14,   14,    1,
        3,    1,    1,    3,    1
    } ;

static const flex_int16_t yy_base[407] =
    {   0,
        0,    0,   55,    0,  536, 1828,  109, 1828,  110,  503,
      507, 1828, 1828, 1828, 1828,  115, 1828,  156,  111,  202,
        0, 1828,  108,  114,  132,   97,   99,  121,  137,  117,
      151,  119, 1828,  248,  125,  460,  163,    0,  488,  480,
      177,  183,  169,    0,  478,  186,  294,  340,  213,  366,
      412,  463,  463,  184, 1828,  514,  218,  560,    0,  458,
      150,  227,  243,  253,  260,  448,  185,  269,  221,  244,
      263,  265,  297,  268,  301,  305,  312,  324,  351,  362,
      373,  381,  343,  375,  378,  398,  409,  417,  411,  423,
      430,  428,  435,  434,  441,  381,  460, 1828,  481,  415,

        0,  400,  586,  491,    0,  398,  523,  543,  632,  591,
      608,  470,  396,  211,  646,  534,  570,  302,  662,  276,
      490,    0, 1828, 1828,  672,    0,  387,  276,  610,  680,
      318,  689,  623,  694,  705,  325,  710,  715,  637,  347,
      741, 1828,  305,  368, 1828,  726,  537,  728,  744,  750,
      597,  476,  752,  748,  755,  770,  774,  585,  782,  785,
      788,  790,  793,  796,  804,  812,  816,  835,  838,  331,
      844,  392,  617,    0,  855,  675,  720,    0, 1828,  863,
      807,  872,  373,  881,  892,  858,  901,  909,  917,  922,
      926,  929,    0,  815,  314,  937,  940,  943,    0,  956,

      960,    0,  356,  335,  961,  355,  364,  977,  986,  965,
     1011,    0,  330,  299,  973, 1008, 1015, 1057, 1024, 1103,
        0,  279, 1033, 1066,  264,  227, 1022, 1042, 1064, 1069,
     1044, 1071, 1075, 1089, 1100, 1111, 1113, 1115, 1117, 1119,
     1130, 1133, 1135, 1828, 1137, 1152,  996, 1155, 1828,  214,
     1158, 1167,  371, 1162, 1171, 1174,  523, 1187,  434,  569,
     1195, 1204,  233, 1211, 1178, 1219, 1192,  542, 1222, 1229,
     1232, 1241,  617, 1828, 1251,    0,  206,  698, 1255, 1264,
     1236, 1272, 1828, 1282,    0,  200, 1828, 1292,    0,  197,
     1295, 1304, 1307, 1311, 1316, 1314, 1141, 1218, 1271, 1277,

     1319, 1327, 1332, 1344,  188, 1828, 1351, 1339, 1358,  742,
     1366, 1375, 1362, 1383, 1386, 1399, 1390, 1403, 1828, 1410,
     1417, 1420, 1423,    0, 1426, 1439, 1435, 1442, 1445,    0,
     1452, 1455, 1458,    0, 1461, 1464, 1469, 1467, 1472, 1828,
     1828, 1485, 1494, 1491, 1503, 1498, 1511, 1507, 1516, 1519,
     1528,  777, 1523, 1532,  845, 1535, 1544,  875, 1539, 1828,
     1554, 1828, 1561, 1828, 1568, 1566, 1540, 1577, 1572, 1586,
     1582, 1591, 1589, 1828, 1612,  192, 1625, 1636, 1646, 1658,
      171, 1670,  153, 1683, 1696,  137, 1708, 1719, 1729,  245,
     1742, 1755, 1768, 1779,  662,  703,  780,  117, 1789,  107,

     1801,  101, 1813,  821,  911,  915
    } ;

static const flex_int16_t yy_def[407] =
    {   0,
      374,    1,  374,    3,  374,  374,  374,  374,  375,  376,
      374,  374,  374,  374,  374,  374,  374,  377,  374,  375,
      378,  374,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  374,  379,   20,  374,  380,  381,  374,  382,
      374,  374,   20,  383,  374,  374,  384,  374,  374,  379,
      385,  385,  374,  374,  374,  377,   56,   56,  386,  374,
      374,  374,   56,   56,   58,  387,  374,  374,   20,  388,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   50,   20,  374,  380,  374,  374,  382,

      381,  374,  384,  374,  383,  374,  374,  374,  384,  374,
      374,  109,  389,  374,  374,  374,  374,  374,  109,   52,
       52,  390,  374,  374,  374,  386,  374,  374,  391,  374,
      374,  374,  392,   56,   58,  374,   56,   56,  374,  374,
      393,  374,  388,  394,  374,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  374,   20,  374,
      374,  374,  374,  395,  374,  374,  119,  396,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  103,   48,   52,  390,  374,  374,  374,  397,  391,

      391,  398,  374,  399,  374,  374,  374,  374,  374,  392,
      392,  400,  374,  401,  374,   56,   56,  393,  218,  218,
      402,  374,  218,  220,  403,  394,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,  374,   20,  374,  374,  374,  374,  374,
      374,  374,  395,  374,  374,  103,  396,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  119,   52,  119,  374,
      374,  374,  397,  374,  374,  398,  374,  374,  374,  374,
      374,  374,  374,  374,  400,  374,  374,  374,  402,  374,
      218,  220,  374,  218,  218,   20,   20,   20,   20,   20,

       20,   20,  374,  374,  374,  374,  374,  119,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  404,  374,  374,  374,  374,  374,  405,
      374,  374,  374,  406,  374,  218,  218,   20,   20,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  404,  374,  374,  405,  374,  374,  406,   20,  374,
      374,  374,  374,  374,  374,   20,  374,  374,  374,  374,
      374,  374,   20,    0,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374
    } ;

static const flex_int16_t yy_nxt[1884] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   18,   18,    9,    9,   19,   20,
       21,    6,   22,    9,   23,    9,   24,    9,   25,   26,
        9,    9,    9,    9,   27,    9,   28,    9,    9,   29,
       30,   31,   32,    9,    9,    9,   33,   34,   34,    6,
        9,    6,    6,   35,   36,    8,    8,    8,    8,   37,
       38,   39,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   37,   37,    8,   37,    8,    8,    8,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,    8,   40,   40,    8,   37,    8,    8,   37,    8,
       41,  289,   41,   42,   67,   44,   45,  285,   54,   68,
       43,   46,   43,   47,   48,   48,   55,  276,   56,   56,
       56,   43,   49,   71,   72,   84,   85,   43,   76,   77,
       43,   83,   92,   93,   43,   88,   78,  126,   43,   73,
       74,   79,   75,  128,   80,   43,   86,   50,   50,   57,
       43,   59,   60,  105,   61,   62,   62,   63,  129,   64,
       64,   64,   81,   65,   43,   95,   98,   82,   41,   87,
       41,  101,  103,   89,   65,   99,   42,   54,   67,   90,
       91,  104,   43,   68,   46,  123,   48,   48,   48,  107,

      107,  107,   51,   66,   66,   42,  341,   44,   45,  334,
      100,  100,  330,   46,  114,   47,   48,   48,  324,  117,
      110,  110,  118,  118,   49,   69,  119,  119,  119,  374,
      130,  374,  374,  374,  103,   58,  263,  305,  131,  142,
      132,  132,  132,  104,   43,  133,   58,  195,  145,   50,
       50,   42,  144,   44,   45,  195,  134,  134,  134,   46,
      135,   47,   48,   48,   63,  145,   64,   64,   64,  136,
      136,  135,  139,  137,  138,  138,  103,  287,  103,  128,
      140,  103,  141,  141,  141,  104,   43,  104,   43,  193,
      104,   43,  149,  290,  129,   50,   50,  108,  168,   44,

       45,  120,  147,  110,  110,  111,  146,   48,   48,   48,
      103,  112,  283,  144,  103,  119,  119,  119,  103,  104,
       43,  269,  112,  104,   43,  103,  145,  104,   43,  148,
      150,  205,  205,  205,  104,   43,  270,  103,  138,  138,
      138,  113,  113,  114,  286,  151,  104,   43,  274,  110,
      110,  115,  152,   48,   48,   48,  103,  116,  206,  153,
      218,  218,  218,  207,  103,  104,   43,  278,  116,   42,
      277,   44,   45,  104,   43,  103,  263,   46,   98,  103,
       48,   48,  133,  250,  104,   43,  103,  154,  103,  145,
      156,  103,  155,  307,  103,  104,   43,  104,   43,  199,

      104,   43,  157,  104,   43,  173,  173,  173,  159,  179,
      178,  103,  174,   50,   50,   42,  109,   44,   45,  158,
      104,   43,  103,   46,  103,   48,   48,   48,   98,  170,
      103,  104,   43,  104,   43,  109,  103,  259,  160,  104,
       43,  103,  260,  103,  162,  104,   43,  163,  103,  161,
      104,   43,  104,   43,  103,  164,  168,  104,   43,  113,
      113,  124,  109,  104,  169,  109,   42,  109,   44,   45,
      165,  167,  127,   98,   46,  122,   48,   48,   48,  186,
      186,  166,   99,  187,  188,  188,  109,  171,  121,  103,
      172,  172,  106,   98,  173,  173,  173,  175,  104,   43,

      176,  176,  102,  193,  177,  177,  177,  100,  100,   96,
      113,  113,  168,  109,  194,  120,  109,   57,  233,   59,
       60,   53,   61,   62,   62,  123,  114,   56,   56,   56,
      179,   65,  110,  110,   52,  374,  107,  107,  107,  374,
      116,  374,   65,  186,  186,  309,  108,  188,  188,  188,
      103,  116,  110,  110,   46,  193,   48,   48,   48,  104,
       43,   66,   66,  374,  168,  374,  374,  120,  374,  374,
      374,  374,  310,  124,  374,  374,  374,   58,  228,  190,
      190,  374,  125,  191,  191,  191,  374,  183,   58,  108,
      374,   44,   45,  374,  180,  110,  110,  111,  103,   48,

       48,   48,  181,  112,  182,  182,  182,  104,   43,  183,
      103,  114,  374,  200,  112,  202,  203,  110,  110,  104,
       43,  184,  184,  184,  124,  185,  210,  232,  212,  213,
      173,  173,  173,  113,  113,  374,  185,  374,  374,  320,
      139,  374,  374,  374,  374,  179,  374,  374,  140,  114,
      141,  141,  141,  374,  168,  110,  110,  204,  204,  189,
      189,  189,  374,  185,  253,   42,  374,   44,   45,  374,
      214,  214,  253,   46,  185,  192,  192,  192,  196,  113,
      113,  197,  197,  130,  374,  198,  198,  198,  177,  177,
      177,  131,  206,  132,  132,  132,  374,  207,  133,  374,

      208,  278,  132,  132,  132,  257,  209,  134,  134,  134,
      374,  135,  374,  257,  215,  215,  133,  209,  216,  217,
      217,  374,  135,  138,  138,  138,  374,   58,  138,  138,
      138,  374,   58,  256,  256,  256,  374,  374,   58,  103,
      374,  103,  374,   58,  219,  310,  221,  222,  104,   43,
      104,   43,  223,  374,  141,  141,  141,  103,  224,  374,
      183,  103,  227,  103,  229,  103,  104,   43,  103,  224,
      104,   43,  104,   43,  104,   43,  234,  104,   43,  374,
      230,  235,  273,  103,  274,  374,  236,  103,  225,  225,
      273,  231,  104,   43,  237,  103,  104,   43,  103,  361,

      238,  103,  374,  103,  104,   43,  103,  104,   43,  103,
      104,   43,  104,   43,  374,  104,   43,  103,  104,   43,
      258,  258,  258,  352,  241,  103,  104,   43,  193,  103,
      239,  352,  242,  240,  104,   43,  374,  168,  104,   43,
      120,  246,  374,  374,  247,  247,  243,  245,  248,  248,
      248,  103,  283,  251,  251,  268,  249,  252,  252,  252,
      104,   43,  374,  244,  254,  254,  180,  363,  255,  255,
      255,  188,  188,  188,  181,  259,  182,  182,  182,  374,
      260,  183,  287,  261,  114,  182,  182,  182,  374,  262,
      110,  110,  374,  374,  184,  184,  184,  365,  264,  374,

      262,  265,  265,  374,  114,  266,  266,  266,  374,  264,
      110,  110,  114,  355,  188,  188,  188,  358,  110,  110,
      114,  355,  188,  188,  188,  358,  110,  110,  374,  374,
      189,  189,  189,  267,  185,  191,  191,  191,  374,  191,
      191,  191,  192,  192,  192,  185,  271,  271,  374,  374,
      272,  272,  272,  198,  198,  198,  198,  198,  198,  200,
      374,  202,  203,  374,  206,  374,  374,  374,  210,  207,
      212,  213,  374,  274,  205,  205,  205,  374,  209,  374,
      206,  374,  275,  374,  374,  207,  217,  217,  217,  209,
      279,  279,  279,  374,  280,  281,  281,  374,  374,  282,

      282,  282,  374,  204,  204,  280,  374,  204,  204,  248,
      248,  248,  214,  214,  374,  374,  374,  374,  374,  374,
      374,  217,  217,  217,  283,   58,  374,  374,  217,  217,
      217,  374,   58,  284,  374,  103,   58,  374,  374,  374,
      374,  220,  374,   58,  104,   43,  291,  291,  291,  296,
      292,  374,  220,  374,  374,  103,  374,  103,  214,  214,
      219,  292,  221,  222,  104,   43,  104,   43,  374,  374,
      218,  218,  218,  297,  224,  293,  293,  103,  374,  294,
      295,  295,  103,  374,  103,  224,  104,   43,  103,  374,
      374,  104,   43,  104,   43,  298,  374,  104,   43,  374,

      299,  374,  103,  374,  225,  225,  374,  374,  374,  374,
      374,  104,   43,  103,  374,  374,  287,  374,  374,  300,
      220,  374,  104,   43,  103,  288,  103,  374,  103,  374,
      103,  220,  103,  104,   43,  104,   43,  104,   43,  104,
       43,  104,   43,  103,  374,  302,  103,  301,  103,  374,
      103,  374,  104,   43,  103,  104,   43,  104,   43,  104,
       43,  303,  303,  104,   43,  304,  304,  304,  248,  248,
      248,  252,  252,  252,  306,  255,  255,  255,  308,  374,
      252,  252,  252,  374,  255,  255,  255,  256,  256,  256,
      259,  266,  266,  266,  374,  260,  374,  374,  259,  374,

      258,  258,  258,  260,  262,   48,   48,   48,  311,  311,
      311,  374,  312,  313,  313,  262,  374,  314,  314,  314,
      315,  315,  114,  312,  316,  316,  316,  374,  110,  110,
      374,  103,  266,  266,  266,   48,   48,   48,  317,  317,
      104,   43,  318,  318,  318,  272,  272,  272,  319,  282,
      282,  282,  374,  374,  272,  272,  272,  321,  206,  374,
      322,  322,  374,  207,  323,  323,  323,  374,  279,  279,
      279,  374,  280,  325,  325,  206,  374,  326,  326,  326,
      207,  374,  374,  280,  103,  282,  282,  282,  327,  374,
      103,  328,  328,  104,   43,  329,  329,  329,  331,  104,

       43,  332,  332,  374,  374,  333,  333,  333,  291,  291,
      291,  374,  292,  335,  335,  374,  374,  336,  337,  337,
      295,  295,  295,  292,  295,  295,  295,  103,  220,  295,
      295,  295,  103,  220,  374,  374,  104,   43,  338,  220,
      103,  104,   43,  374,  220,  304,  304,  304,  374,  104,
       43,  340,   48,   48,   48,  339,  374,  304,  304,  304,
      342,  342,  374,  374,  343,  343,  343,  344,  344,  259,
      374,  345,  345,  345,  260,  314,  314,  314,  374,  311,
      311,  311,  374,  312,  346,  346,  259,  374,  347,  347,
      347,  260,  374,  374,  312,  374,  314,  314,  314,  316,

      316,  316,  114,  318,  318,  318,  374,  374,  110,  110,
      269,  374,  316,  316,  316,  374,  318,  318,  318,  348,
      348,  374,  374,  349,  349,  349,  350,  350,  374,  374,
      351,  351,  351,  323,  323,  323,  323,  323,  323,  326,
      326,  326,  206,  374,  353,  353,  374,  207,  354,  354,
      354,  374,  326,  326,  326,  329,  329,  329,  329,  329,
      329,  356,  356,  374,  374,  357,  357,  357,  333,  333,
      333,  333,  333,  333,  337,  337,  337,  337,  337,  337,
      103,  220,  337,  337,  337,  103,  220,  374,  374,  104,
       43,  374,  220,  374,  104,   43,  374,  220,  343,  343,

      343,   98,  374,  359,  345,  345,  345,  343,  343,  343,
      179,  347,  347,  347,  259,  374,  345,  345,  345,  260,
      349,  349,  349,  124,  347,  347,  347,  374,  374,  349,
      349,  349,  351,  351,  351,  360,  354,  354,  354,  362,
      374,  351,  351,  351,  374,  354,  354,  354,  357,  357,
      357,  364,  103,  368,  368,  368,  374,  357,  357,  357,
      374,  104,   43,  367,  367,  366,  374,  368,  368,  368,
      369,  369,  374,  374,  370,  370,  370,  371,  371,  103,
      374,  372,  372,  372,  274,  370,  370,  370,  104,   43,
      368,  368,  368,  283,  373,  372,  372,  372,  287,  370,

      370,  370,  103,  374,  372,  372,  372,  374,  374,  374,
      374,  104,   43,   43,   43,   43,  374,  374,  374,   43,
       43,   43,   43,  374,   43,   43,   58,   58,   58,  374,
       58,   58,   58,   58,   58,   58,  374,  374,   58,   70,
       70,  374,  374,  374,  374,  374,   70,   94,   94,   94,
      374,  374,  374,   94,   94,   94,   94,  374,  374,   94,
       97,  374,  374,  374,  374,  374,   97,  374,   97,  374,
       97,   97,  100,  374,  374,  374,  374,  374,  100,  374,
      100,  374,  374,  100,  109,  109,  109,  374,  374,  109,
      109,  109,  109,  109,  374,  374,  109,  120,  120,  120,

      374,  374,  374,  120,  120,  120,  120,  374,  374,  120,
       66,  374,  374,  374,  374,  374,   66,  374,   66,  374,
      374,   66,  143,  143,  143,  374,  374,  143,  143,  143,
      143,  113,  374,  374,  374,  374,  374,  113,  374,  113,
      374,  374,  113,  201,  201,  201,  374,  374,  374,  374,
      374,  374,  201,  374,  374,  201,  211,  211,  211,  374,
      374,  374,  374,  374,  374,  211,  374,  374,  211,  220,
      220,  220,  374,  374,  374,  220,  220,  220,  220,  374,
      374,  220,  226,  226,  374,  374,  374,  226,  226,  226,
      226,  204,  374,  374,  374,  374,  374,  204,  374,  204,

      374,  374,  204,  214,  374,  374,  374,  374,  374,  214,
      374,  214,  374,  374,  214,  225,  374,  374,  374,  374,
      374,  225,  374,  225,  374,  374,  225,    5,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374
    } ;

static const flex_int16_t yy_chk[1884] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        7,  402,    7,    9,   19,    9,    9,  400,   16,   19,
       26,    9,   27,    9,    9,    9,   16,  398,   16,   16,
       16,   23,    9,   23,   23,   27,   27,   24,   24,   24,
       30,   26,   32,   32,   28,   30,   24,  386,   35,   23,
       23,   24,   23,   61,   24,   25,   28,    9,    9,   18,
       29,   18,   18,  383,   18,   18,   18,   18,   61,   18,
       18,   18,   25,   18,   31,   35,   37,   25,   41,   29,
       41,  381,   43,   31,   18,   37,   42,   54,   67,   31,
       31,   43,   43,   67,   42,   54,   42,   42,   42,   46,

       46,   46,  376,   18,   18,   20,  305,   20,   20,  290,
       37,   37,  286,   20,  114,   20,   20,   20,  277,   49,
      114,  114,   49,   49,   20,   20,   49,   49,   49,   57,
       62,   57,   57,   57,   69,   57,  263,  250,   62,   69,
       62,   62,   62,   69,   69,   62,   57,  390,  226,   20,
       20,   34,   70,   34,   34,  390,   63,   63,   63,   34,
       63,   34,   34,   34,   64,   70,   64,   64,   64,   65,
       65,   63,   68,   65,   65,   65,   71,  225,   72,  128,
       68,   74,   68,   68,   68,   71,   71,   72,   72,  120,
       74,   74,   74,  222,  128,   34,   34,   47,  120,   47,

       47,  120,   72,   47,   47,   47,   71,   47,   47,   47,
       73,   47,  214,  143,   75,  118,  118,  118,   76,   73,
       73,  195,   47,   75,   75,   77,  143,   76,   76,   73,
       76,  131,  131,  131,   77,   77,  195,   78,  136,  136,
      136,   47,   47,   48,  213,   76,   78,   78,  204,   48,
       48,   48,   77,   48,   48,   48,   83,   48,  206,   78,
      140,  140,  140,  206,   79,   83,   83,  207,   48,   50,
      203,   50,   50,   79,   79,   80,  183,   50,  253,   50,
       50,   50,  207,  170,   80,   80,   81,   79,   84,  144,
       80,   85,   79,  253,   82,   81,   81,   84,   84,  127,

       85,   85,   81,   82,   82,  172,  172,  172,   85,  113,
      106,   86,  102,   50,   50,   51,   51,   51,   51,   82,
       86,   86,   87,   51,   89,   51,   51,   51,  100,   96,
       88,   87,   87,   89,   89,   51,   90,  259,   86,   88,
       88,   92,  259,   91,   88,   90,   90,   89,   93,   87,
       92,   92,   91,   91,   95,   90,   94,   93,   93,   51,
       51,   66,   51,   95,   95,   51,   52,   52,   52,   52,
       91,   93,   60,   97,   52,   53,   52,   52,   52,  112,
      112,   92,   97,  112,  112,  112,   52,   99,   52,  152,
       99,   99,   45,   40,   99,   99,   99,  104,  152,  152,

      104,  104,   39,  121,  104,  104,  104,   97,   97,   36,
       52,   52,  121,   52,  121,  121,   52,   56,  152,   56,
       56,   11,   56,   56,   56,   56,  107,   56,   56,   56,
      257,   56,  107,  107,   10,    5,  107,  107,  107,    0,
      107,    0,   56,  116,  116,  257,  108,  116,  116,  116,
      147,  107,  108,  108,  108,  268,  108,  108,  108,  147,
      147,   56,   56,   58,  268,   58,   58,  268,   58,   58,
       58,   58,  260,   58,   58,   58,    0,   58,  147,  117,
      117,    0,   58,  117,  117,  117,    0,  260,   58,  103,
        0,  103,  103,    0,  110,  103,  103,  103,  158,  103,

      103,  103,  110,  103,  110,  110,  110,  158,  158,  110,
      151,  111,    0,  129,  103,  129,  129,  111,  111,  151,
      151,  111,  111,  111,  273,  111,  133,  151,  133,  133,
      173,  173,  173,  103,  103,  109,  111,  109,  109,  273,
      139,  109,  109,  109,    0,  109,  109,  109,  139,  115,
      139,  139,  139,    0,  109,  115,  115,  129,  129,  115,
      115,  115,    0,  115,  395,  119,    0,  119,  119,    0,
      133,  133,  395,  119,  115,  119,  119,  119,  125,  109,
      109,  125,  125,  130,  119,  125,  125,  125,  176,  176,
      176,  130,  132,  130,  130,  130,    0,  132,  130,    0,

      132,  278,  132,  132,  132,  396,  132,  134,  134,  134,
        0,  134,    0,  396,  135,  135,  278,  132,  135,  135,
      135,  137,  134,  137,  137,  137,  138,  137,  138,  138,
      138,    0,  138,  177,  177,  177,    0,    0,  137,  146,
        0,  148,    0,  138,  141,  310,  141,  141,  146,  146,
      148,  148,  141,    0,  141,  141,  141,  149,  141,    0,
      310,  154,  146,  150,  148,  153,  149,  149,  155,  141,
      154,  154,  150,  150,  153,  153,  153,  155,  155,    0,
      149,  154,  397,  156,  352,    0,  155,  157,  141,  141,
      397,  150,  156,  156,  156,  159,  157,  157,  160,  352,

      157,  161,    0,  162,  159,  159,  163,  160,  160,  164,
      161,  161,  162,  162,    0,  163,  163,  165,  164,  164,
      181,  181,  181,  404,  163,  166,  165,  165,  194,  167,
      161,  404,  164,  162,  166,  166,    0,  194,  167,  167,
      194,  168,    0,    0,  168,  168,  165,  167,  168,  168,
      168,  169,  355,  171,  171,  194,  169,  171,  171,  171,
      169,  169,    0,  166,  175,  175,  180,  355,  175,  175,
      175,  186,  186,  186,  180,  182,  180,  180,  180,    0,
      182,  180,  358,  182,  184,  182,  182,  182,    0,  182,
      184,  184,    0,    0,  184,  184,  184,  358,  184,    0,

      182,  185,  185,    0,  187,  185,  185,  185,    0,  184,
      187,  187,  188,  405,  187,  187,  187,  406,  188,  188,
      189,  405,  188,  188,  188,  406,  189,  189,    0,    0,
      189,  189,  189,  191,  189,  190,  190,  190,    0,  191,
      191,  191,  192,  192,  192,  189,  196,  196,    0,    0,
      196,  196,  196,  197,  197,  197,  198,  198,  198,  200,
        0,  200,  200,  201,  205,  201,  201,    0,  210,  205,
      210,  210,    0,  201,  205,  205,  205,    0,  205,    0,
      208,    0,  201,    0,    0,  208,  215,  215,  215,  205,
      208,  208,  208,    0,  208,  209,  209,    0,    0,  209,

      209,  209,    0,  200,  200,  208,    0,  201,  201,  247,
      247,  247,  210,  210,  211,    0,  211,  211,    0,  216,
        0,  216,  216,  216,  211,  216,  217,    0,  217,  217,
      217,    0,  217,  211,    0,  227,  216,  219,  219,  219,
        0,  219,    0,  217,  227,  227,  223,  223,  223,  227,
      223,    0,  219,    0,    0,  228,    0,  231,  211,  211,
      218,  223,  218,  218,  228,  228,  231,  231,  218,    0,
      218,  218,  218,  228,  218,  224,  224,  229,    0,  224,
      224,  224,  230,    0,  232,  218,  229,  229,  233,    0,
        0,  230,  230,  232,  232,  229,    0,  233,  233,    0,

      230,    0,  234,    0,  218,  218,  220,    0,  220,  220,
        0,  234,  234,  235,    0,    0,  220,  220,  220,  234,
      220,    0,  235,  235,  236,  220,  237,    0,  238,    0,
      239,  220,  240,  236,  236,  237,  237,  238,  238,  239,
      239,  240,  240,  241,    0,  240,  242,  237,  243,    0,
      245,    0,  241,  241,  297,  242,  242,  243,  243,  245,
      245,  246,  246,  297,  297,  246,  246,  246,  248,  248,
      248,  251,  251,  251,  252,  254,  254,  254,  255,    0,
      252,  252,  252,    0,  255,  255,  255,  256,  256,  256,
      258,  265,  265,  265,    0,  258,    0,    0,  261,    0,

      258,  258,  258,  261,  258,  267,  267,  267,  261,  261,
      261,    0,  261,  262,  262,  258,    0,  262,  262,  262,
      264,  264,  266,  261,  264,  264,  264,    0,  266,  266,
        0,  298,  266,  266,  266,  269,  269,  269,  270,  270,
      298,  298,  270,  270,  270,  271,  271,  271,  272,  281,
      281,  281,    0,    0,  272,  272,  272,  275,  279,    0,
      275,  275,    0,  279,  275,  275,  275,    0,  279,  279,
      279,    0,  279,  280,  280,  282,    0,  280,  280,  280,
      282,    0,    0,  279,  299,  282,  282,  282,  284,    0,
      300,  284,  284,  299,  299,  284,  284,  284,  288,  300,

      300,  288,  288,    0,    0,  288,  288,  288,  291,  291,
      291,    0,  291,  292,  292,    0,    0,  292,  292,  292,
      293,  293,  293,  291,  294,  294,  294,  296,  294,  295,
      295,  295,  301,  295,    0,    0,  296,  296,  296,  294,
      302,  301,  301,    0,  295,  303,  303,  303,    0,  302,
      302,  304,  308,  308,  308,  302,    0,  304,  304,  304,
      307,  307,    0,    0,  307,  307,  307,  309,  309,  311,
        0,  309,  309,  309,  311,  313,  313,  313,    0,  311,
      311,  311,    0,  311,  312,  312,  314,    0,  312,  312,
      312,  314,    0,    0,  311,    0,  314,  314,  314,  315,

      315,  315,  316,  317,  317,  317,    0,    0,  316,  316,
      318,    0,  316,  316,  316,    0,  318,  318,  318,  320,
      320,    0,    0,  320,  320,  320,  321,  321,    0,    0,
      321,  321,  321,  322,  322,  322,  323,  323,  323,  325,
      325,  325,  326,    0,  327,  327,    0,  326,  327,  327,
      327,    0,  326,  326,  326,  328,  328,  328,  329,  329,
      329,  331,  331,    0,    0,  331,  331,  331,  332,  332,
      332,  333,  333,  333,  335,  335,  335,  336,  336,  336,
      338,  336,  337,  337,  337,  339,  337,    0,    0,  338,
      338,    0,  336,    0,  339,  339,    0,  337,  342,  342,

      342,  343,    0,  338,  344,  344,  344,  343,  343,  343,
      345,  346,  346,  346,  347,    0,  345,  345,  345,  347,
      348,  348,  348,  349,  347,  347,  347,    0,    0,  349,
      349,  349,  350,  350,  350,  351,  353,  353,  353,  354,
        0,  351,  351,  351,    0,  354,  354,  354,  356,  356,
      356,  357,  359,  367,  367,  367,    0,  357,  357,  357,
        0,  359,  359,  361,  361,  359,    0,  361,  361,  361,
      363,  363,    0,    0,  363,  363,  363,  365,  365,  366,
        0,  365,  365,  365,  368,  369,  369,  369,  366,  366,
      368,  368,  368,  370,  366,  371,  371,  371,  372,  370,

      370,  370,  373,    0,  372,  372,  372,    0,    0,    0,
        0,  373,  373,  375,  375,  375,    0,    0,    0,  375,
      375,  375,  375,    0,  375,  375,  377,  377,  377,    0,
      377,  377,  377,  377,  377,  377,    0,    0,  377,  378,
      378,    0,    0,    0,    0,    0,  378,  379,  379,  379,
        0,    0,    0,  379,  379,  379,  379,    0,    0,  379,
      380,    0,    0,    0,    0,    0,  380,    0,  380,    0,
      380,  380,  382,    0,    0,    0,    0,    0,  382,    0,
      382,    0,    0,  382,  384,  384,  384,    0,    0,  384,
      384,  384,  384,  384,    0,    0,  384,  385,  385,  385,

        0,    0,    0,  385,  385,  385,  385,    0,    0,  385,
      387,    0,    0,    0,    0,    0,  387,    0,  387,    0,
        0,  387,  388,  388,  388,    0,    0,  388,  388,  388,
      388,  389,    0,    0,    0,    0,    0,  389,    0,  389,
        0,    0,  389,  391,  391,  391,    0,    0,    0,    0,
        0,    0,  391,    0,    0,  391,  392,  392,  392,    0,
        0,    0,    0,    0,    0,  392,    0,    0,  392,  393,
      393,  393,    0,    0,    0,  393,  393,  393,  393,    0,
        0,  393,  394,  394,    0,    0,    0,  394,  394,  394,
      394,  399,    0,    0,    0,    0,    0,  399,    0,  399,

        0,    0,  399,  401,    0,    0,    0,    0,    0,  401,
        0,  401,    0,    0,  401,  403,    0,    0,    0,    0,
        0,  403,    0,  403,    0,    0,  403,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/SIScalarScanner.l"
#line 4 "src/SIScalarScanner.l"
    extern  void siserror(char *s, ...);
    #include "SILibrary.h"
    #include "SIScalarParser.h"
    #include "SIScalar.tab.h"
    static double complex temp;
#line 1345 "src/SIScalarScanner.c"

/* exponent */
/* unit can be constant starting with &
 unit can be constant ending with 0
 unit can be symbol raised to arbitrary power.
 */
#line 1352 "src/SIScalarScanner.c"

#define INITIAL 0
#define together 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "src/SIScalarScanner.l"

#line 1578 "src/SIScalarScanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 375 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1828 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
#line 41 "src/SIScalarScanner.l"
case 2:
#line 42 "src/SIScalarScanner.l"
case 3:
#line 43 "src/SIScalarScanner.l"
case 4:
#line 44 "src/SIScalarScanner.l"
case 5:
#line 45 "src/SIScalarScanner.l"
case 6:
#line 46 "src/SIScalarScanner.l"
case 7:
#line 47 "src/SIScalarScanner.l"
case 8:
YY_RULE_SETUP
#line 47 "src/SIScalarScanner.l"
{return yytext[0];}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "src/SIScalarScanner.l"
{sislval.math_fn = BM_acos; return MATH_FUNC;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "src/SIScalarScanner.l"
{sislval.math_fn = BM_acosh; return MATH_FUNC;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "src/SIScalarScanner.l"
{sislval.math_fn = BM_asin; return MATH_FUNC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "src/SIScalarScanner.l"
{sislval.math_fn = BM_asinh; return MATH_FUNC;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "src/SIScalarScanner.l"
{sislval.math_fn = BM_atan; return MATH_FUNC;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "src/SIScalarScanner.l"
{sislval.math_fn = BM_atanh; return MATH_FUNC;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cos; return MATH_FUNC;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cosh; return MATH_FUNC;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sin; return MATH_FUNC;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sinh; return MATH_FUNC;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "src/SIScalarScanner.l"
{sislval.math_fn = BM_tan; return MATH_FUNC;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "src/SIScalarScanner.l"
{sislval.math_fn = BM_tanh; return MATH_FUNC;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "src/SIScalarScanner.l"
{sislval.math_fn = BM_erf; return MATH_FUNC;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "src/SIScalarScanner.l"
{sislval.math_fn = BM_erfc; return MATH_FUNC;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "src/SIScalarScanner.l"
{sislval.math_fn = BM_exp; return MATH_FUNC;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "src/SIScalarScanner.l"
{sislval.math_fn = BM_ln; return MATH_FUNC;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "src/SIScalarScanner.l"
{sislval.math_fn = BM_log; return MATH_FUNC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "src/SIScalarScanner.l"
{sislval.math_fn = BM_conj; return MATH_FUNC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "src/SIScalarScanner.l"
{sislval.math_fn = BM_creal; return MATH_FUNC;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cimag; return MATH_FUNC;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "src/SIScalarScanner.l"
{sislval.math_fn = BM_carg; return MATH_FUNC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cabs; return MATH_FUNC;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sqrt; return MATH_FUNC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cbrt; return MATH_FUNC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "src/SIScalarScanner.l"
{sislval.math_fn = BM_qtrt; return MATH_FUNC;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "src/SIScalarScanner.l"
{sislval.math_fn = BM_reduce; return MATH_FUNC;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "src/SIScalarScanner.l"
{sislval.const_fn = BC_AW; return CONST_FUNC;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "src/SIScalarScanner.l"
{sislval.const_fn = BC_FW; return CONST_FUNC;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Abundance; return CONST_FUNC;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Gyromag; return CONST_FUNC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_MagneticDipole; return CONST_FUNC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_ElectricQuadrupole; return CONST_FUNC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "src/SIScalarScanner.l"
{sislval.const_fn = BC_nmr; return CONST_FUNC;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Spin; return CONST_FUNC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_HalfLife; return CONST_FUNC;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "src/SIScalarScanner.l"
{double multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(STR("ℏ"),&multiplier, &scalarErrorString);
    sislval.d = SIScalarCreateWithDouble(multiplier,unit);
    return SCALAR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 122 "src/SIScalarScanner.l"
{
    OCStringRef string = OCStringCreateWithCString(yytext);
    double unit_multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(string, &unit_multiplier, &scalarErrorString);
    if(unit == NULL) {
        yyterminate();
    }
    sislval.d = SIScalarCreateWithDouble(unit_multiplier, unit);
    OCRelease(string);
    return SCALAR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 134 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 139 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 154 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 163 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "src/SIScalarScanner.l"
{
    OCStringRef string = OCStringCreateWithCString(yytext);
    double unit_multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(string, &unit_multiplier,&scalarErrorString);
    if(unit==NULL) {
        yyterminate();
        if(string) OCRelease(string);
        BEGIN(INITIAL);
        return SCALAR;
    }
    sislval.d = SIScalarCreateWithDoubleComplex(temp*unit_multiplier, unit);
    OCRelease(string);
    BEGIN(INITIAL);
    return SCALAR;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 186 "src/SIScalarScanner.l"
{
    sislval.const_string = OCMutableStringCreateWithCString(yytext);
    return CONST_STRING;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 190 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 194 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 198 "src/SIScalarScanner.l"
{/* ignore whitespace */}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 199 "src/SIScalarScanner.l"
{return(yytext[0]);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 200 "src/SIScalarScanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2043 "src/SIScalarScanner.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(together):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 375 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 375 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 374);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "src/SIScalarScanner.l"


