#line 1 "src/SIScalarScanner.c"

#line 3 "src/SIScalarScanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer sis_create_buffer
#define yy_delete_buffer sis_delete_buffer
#define yy_scan_buffer sis_scan_buffer
#define yy_scan_string sis_scan_string
#define yy_scan_bytes sis_scan_bytes
#define yy_init_buffer sis_init_buffer
#define yy_flush_buffer sis_flush_buffer
#define yy_load_buffer_state sis_load_buffer_state
#define yy_switch_to_buffer sis_switch_to_buffer
#define yypush_buffer_state sispush_buffer_state
#define yypop_buffer_state sispop_buffer_state
#define yyensure_buffer_stack sisensure_buffer_stack
#define yy_flex_debug sis_flex_debug
#define yyin sisin
#define yyleng sisleng
#define yylex sislex
#define yylineno sislineno
#define yyout sisout
#define yyrestart sisrestart
#define yytext sistext
#define yywrap siswrap
#define yyalloc sisalloc
#define yyrealloc sisrealloc
#define yyfree sisfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define sis_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer sis_create_buffer
#endif

#ifdef yy_delete_buffer
#define sis_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer sis_delete_buffer
#endif

#ifdef yy_scan_buffer
#define sis_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer sis_scan_buffer
#endif

#ifdef yy_scan_string
#define sis_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string sis_scan_string
#endif

#ifdef yy_scan_bytes
#define sis_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes sis_scan_bytes
#endif

#ifdef yy_init_buffer
#define sis_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer sis_init_buffer
#endif

#ifdef yy_flush_buffer
#define sis_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer sis_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define sis_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state sis_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define sis_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer sis_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define sispush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state sispush_buffer_state
#endif

#ifdef yypop_buffer_state
#define sispop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state sispop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define sisensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack sisensure_buffer_stack
#endif

#ifdef yylex
#define sislex_ALREADY_DEFINED
#else
#define yylex sislex
#endif

#ifdef yyrestart
#define sisrestart_ALREADY_DEFINED
#else
#define yyrestart sisrestart
#endif

#ifdef yylex_init
#define sislex_init_ALREADY_DEFINED
#else
#define yylex_init sislex_init
#endif

#ifdef yylex_init_extra
#define sislex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra sislex_init_extra
#endif

#ifdef yylex_destroy
#define sislex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy sislex_destroy
#endif

#ifdef yyget_debug
#define sisget_debug_ALREADY_DEFINED
#else
#define yyget_debug sisget_debug
#endif

#ifdef yyset_debug
#define sisset_debug_ALREADY_DEFINED
#else
#define yyset_debug sisset_debug
#endif

#ifdef yyget_extra
#define sisget_extra_ALREADY_DEFINED
#else
#define yyget_extra sisget_extra
#endif

#ifdef yyset_extra
#define sisset_extra_ALREADY_DEFINED
#else
#define yyset_extra sisset_extra
#endif

#ifdef yyget_in
#define sisget_in_ALREADY_DEFINED
#else
#define yyget_in sisget_in
#endif

#ifdef yyset_in
#define sisset_in_ALREADY_DEFINED
#else
#define yyset_in sisset_in
#endif

#ifdef yyget_out
#define sisget_out_ALREADY_DEFINED
#else
#define yyget_out sisget_out
#endif

#ifdef yyset_out
#define sisset_out_ALREADY_DEFINED
#else
#define yyset_out sisset_out
#endif

#ifdef yyget_leng
#define sisget_leng_ALREADY_DEFINED
#else
#define yyget_leng sisget_leng
#endif

#ifdef yyget_text
#define sisget_text_ALREADY_DEFINED
#else
#define yyget_text sisget_text
#endif

#ifdef yyget_lineno
#define sisget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno sisget_lineno
#endif

#ifdef yyset_lineno
#define sisset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno sisset_lineno
#endif

#ifdef yywrap
#define siswrap_ALREADY_DEFINED
#else
#define yywrap siswrap
#endif

#ifdef yyalloc
#define sisalloc_ALREADY_DEFINED
#else
#define yyalloc sisalloc
#endif

#ifdef yyrealloc
#define sisrealloc_ALREADY_DEFINED
#else
#define yyrealloc sisrealloc
#endif

#ifdef yyfree
#define sisfree_ALREADY_DEFINED
#else
#define yyfree sisfree
#endif

#ifdef yytext
#define sistext_ALREADY_DEFINED
#else
#define yytext sistext
#endif

#ifdef yyleng
#define sisleng_ALREADY_DEFINED
#else
#define yyleng sisleng
#endif

#ifdef yyin
#define sisin_ALREADY_DEFINED
#else
#define yyin sisin
#endif

#ifdef yyout
#define sisout_ALREADY_DEFINED
#else
#define yyout sisout
#endif

#ifdef yy_flex_debug
#define sis_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug sis_flex_debug
#endif

#ifdef yylineno
#define sislineno_ALREADY_DEFINED
#else
#define yylineno sislineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define siswrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[369] =
    {   0,
        0,    0,    0,    0,   64,   62,   61,   63,   50,   62,
        7,    8,    3,    1,    2,   62,    4,   45,   49,   50,
       62,    5,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,    6,   50,   50,   62,   57,   63,   63,   57,
       61,    0,   50,    0,    0,    0,   50,    0,   50,   50,
       50,    0,    0,   59,   45,    0,    0,    0,   45,    0,
       45,    0,    0,    0,   50,    0,   50,   50,   50,   50,
       35,   50,   50,   50,   50,   50,   50,   50,   36,   24,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,    0,   57,   57,    0,   57,   57,    0,   50,    0,

       60,    0,    0,    0,   52,   60,   60,    0,    0,   50,
       50,   50,    0,   59,    0,   47,    0,    0,    0,   46,
       45,    0,    0,   51,    0,    0,   51,    0,   45,    0,
        0,   48,   40,    0,    0,   58,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   15,   50,   21,   23,   25,
       41,   50,   50,   17,   50,   50,   50,   19,    0,   50,
        0,    0,    0,   57,    0,    0,    0,   50,    0,   52,
        0,    0,   52,    0,   60,    0,    0,   50,    0,   47,
        0,    0,    0,    0,    0,    0,   46,    0,    0,   45,
       51,    0,   51,    0,   48,    0,   48,    0,    0,    0,

       50,    9,   11,   13,   30,   29,   32,   50,   26,   16,
       50,   22,   33,   50,   18,   42,   31,   43,   20,    0,
        0,   60,   39,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   53,   52,    0,    0,   52,   50,   44,
        0,    0,   55,    0,    0,   55,    0,    0,    0,    0,
        0,    0,   54,    0,    0,   54,    0,    0,   51,    0,
       48,    0,    0,   56,    0,    0,   56,    0,   48,   50,
       10,   12,   14,   28,   27,   50,    0,    0,    0,   57,
        0,   50,    0,    0,    0,    0,    0,    0,   53,    0,
       52,    0,    0,   55,    0,   55,    0,    0,    0,   54,

        0,   54,    0,    0,    0,    0,    0,   48,   56,    0,
       56,    0,   50,   34,   60,   38,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   55,    0,    0,
        0,   54,    0,   51,    0,    0,    0,   56,    0,   50,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   50,   55,    0,   54,    0,   56,    0,
       37,    0,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,    1,    1,    1,
        1,    1,    1,    1,   17,   17,   17,   17,   18,   17,
       17,   17,   19,   17,   17,   17,   17,   17,   17,   17,
       20,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       21,    1,   22,   23,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,   17,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   17,   45,   46,
       17,   17,    1,   47,    1,    1,    1,    5,    1,    1,
        5,    5,    5,    1,    1,   48,    1,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   49,    1,   50,   48,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    5,   48,    1,    1,    1,
       51,    1,    1,    1,    1,    1,   48,    1,   52,   53,
        1,    1,    1,   54,    5,    1,    1,   48,    1,    1,

        1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   55,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    1,    2,    3,    2,    4,    5,    6,    1,
        1,    1,    7,    8,    9,    9,   10,   10,    5,   10,
        1,    9,   11,    3,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    1,   12,   12,    1,
        3,    1,    1,    3,    1
    } ;

static const flex_int16_t yy_base[401] =
    {   0,
        0,    0,   55,    0,  588, 1723,  109, 1723,  108,  524,
      533, 1723, 1723, 1723, 1723,  112, 1723,  154,  114,  180,
        0, 1723,   93,  108,  101,  105,  106,  115,  116,  124,
      121,  149, 1723,  175,  147,  496,  162,    0,  520,  518,
      173,  186,  177,    0,  501,  193,  208,  220,  212,  258,
      309,  493,  228, 1723,  227,  240,  133,  254,  260,  248,
        0,  269,  213,  286,  280,  211,  223,  294,  296,  263,
      307,  313,  320,  326,  328,  324,  345,  332,  350,  353,
      358,  364,  369,  371,  377,  383,  388,  394,  399,  420,
      407,  441,  405, 1723,  430,  471,    0,  471,  443,  448,

        0,  469,  461,  277,  489,  474,  465,  456,  309,  513,
      460,  488,    0, 1723,  176,  268,  526,  480,  535,  438,
        0,  544,  527,  559,    0,  445,  443,  494,  570,  583,
      553,  588, 1723,  319,  403, 1723,  591,  501,  595,  597,
      547,  599,  602,  613,  617,  625,  619,  632,  638,  640,
      644,  646,  651,  658,  662,  664,  669,  677,  701,  699,
      362,  714,  682,  688,    0,  721,  724,  727,    0,  740,
      428,  745,  761,  752, 1723,  731,  766,  769,  303,  448,
      780,  784,  375,  416,  802,  793,  485,  790,  807,  831,
     1723,  841,    0,  396,  845,  508,  862,  820,  871,  382,

      791,  865,  869,  876,  696,  848,  880,  882,  888,  893,
      895,  900,  908,  911,  913,  919,  925, 1723,  927,  942,
      818,  930, 1723,  372,  945,  954,  529,  949,  958,  549,
      963,  969,  977,  386,  986,  997, 1002, 1010, 1013,  996,
     1020, 1033, 1037,    0,  371,  366,  558, 1038, 1047, 1034,
     1055, 1068, 1073,    0,  351,  331, 1078, 1083, 1086,    0,
     1091, 1113, 1104, 1126,    0,  290,  281, 1098, 1121, 1131,
     1009, 1124, 1127, 1143, 1145, 1147, 1128, 1164,  240, 1723,
     1171, 1148, 1178, 1186,  394,  574, 1194, 1203,  244, 1191,
     1216, 1219, 1228, 1723, 1238,    0,  232, 1223, 1242, 1723,

     1252,    0,  225, 1255, 1264,  627, 1259, 1272, 1723, 1282,
        0,  200, 1267, 1241, 1723, 1723, 1268, 1286, 1291, 1295,
      675, 1304, 1313, 1300, 1321, 1328, 1331, 1334,    0, 1341,
     1344, 1347,    0, 1723, 1354, 1361, 1364, 1367,    0, 1370,
     1371, 1386, 1389, 1398,  725, 1393, 1402,  762, 1405, 1414,
     1409, 1418,  842, 1413, 1723, 1429, 1723, 1436, 1723, 1443,
     1317, 1446, 1455, 1450, 1459, 1462, 1471, 1723, 1486,  196,
     1495, 1504, 1514,  192, 1524,  186, 1535, 1546, 1557, 1566,
     1574, 1584,  182, 1592, 1601, 1609, 1617, 1626, 1637, 1648,
      168, 1658,  152, 1668, 1678,  145, 1686, 1696, 1704, 1712

    } ;

static const flex_int16_t yy_def[401] =
    {   0,
      368,    1,  368,    3,  368,  368,  368,  368,  369,  370,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  369,
      371,  368,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  368,  372,   20,  368,  373,  374,  368,  375,
      368,  368,   20,  376,  368,  368,  377,  368,  372,  378,
      378,  368,  368,  368,   18,  368,  368,  368,   55,  379,
       18,  368,  368,  368,   20,  380,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,  372,
       20,  368,  373,  368,  368,  375,  374,  368,  377,  368,

      376,  368,  368,  368,  368,  377,  381,  368,  368,  106,
       51,   51,  382,  368,  368,  368,  368,  368,  368,  368,
       59,  368,  379,  379,  383,  368,  384,  368,  368,  368,
      368,  368,  368,  380,  385,  368,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,  368,   20,
      368,  368,  368,  368,  386,  368,  368,  110,  387,  368,
      368,  368,  368,  368,  368,  368,  368,   51,  382,  368,
      388,  368,  368,  368,  368,  368,  368,  389,  368,  368,
      368,  368,  383,  368,  368,  368,  368,  390,  368,  385,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,  368,   20,  368,
      368,  368,  368,  368,  368,  368,  386,  368,  368,  387,
      368,  368,  368,  368,  368,  368,  368,  368,  110,   51,
      368,  388,  388,  391,  368,  392,  368,  368,  368,  368,
      368,  389,  389,  393,  368,  394,  368,  368,  368,  395,
      368,  368,  390,  390,  396,  368,  397,  368,  368,   20,
       20,   20,   20,   20,   20,   20,  368,  368,  368,  368,
      368,  110,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  391,  368,  368,  368,  368,

      368,  393,  368,  368,  368,  395,  368,  368,  368,  368,
      396,  368,   20,   20,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  398,  368,
      368,  368,  399,  368,  368,  368,  368,  368,  400,   20,
      368,  368,  368,  368,  398,  368,  368,  399,  368,  368,
      368,  368,  400,   20,  368,  368,  368,  368,  368,  368,
       20,  368,  368,  368,  368,  368,  368,    0,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368

    } ;

static const flex_int16_t yy_nxt[1779] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   18,   18,    9,    9,   19,   20,
       21,    6,   22,    9,   23,    9,   24,    9,   25,   26,
        9,    9,    9,    9,   27,    9,   28,    9,    9,   29,
       30,   31,   32,    9,    9,    9,   33,   34,   34,    6,
        9,    6,    6,   35,   36,    8,    8,    8,    8,   37,
       38,   39,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   37,   37,    8,   37,    8,    8,    8,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,    8,   40,   40,    8,   37,    8,    8,   37,    8,
       41,   42,   41,   44,   45,   53,   43,   63,   67,   68,
       46,   47,   64,   54,   43,   55,   55,   55,   43,   43,
       48,   43,   72,   73,   69,   70,  115,   71,   43,   43,
       74,   77,   80,   81,   43,   75,   78,   43,   76,   79,
       82,  116,   84,   85,  311,   49,   49,   56,   83,   86,
       87,  302,   57,   58,   58,   59,   60,   61,   61,   61,
       43,   62,   88,   89,   41,   94,   41,  296,   42,  115,
       44,   45,   62,   42,   95,   44,   45,   46,   47,   42,
       99,  193,   46,   47,  116,  101,  103,   91,   46,  100,

       43,   97,   48,   65,  104,   50,  105,  105,  105,   96,
       96,   42,  339,   44,   45,   42,   63,   44,   45,  135,
       46,   64,   49,   49,   46,   99,  108,   49,   49,  109,
      109,   53,  136,  110,  110,  110,   99,  333,  114,  114,
       55,   55,   55,   56,  329,  100,   43,  289,   57,   58,
       58,  123,   60,  125,  126,  107,  107,  117,  316,   49,
       49,   42,  106,   44,   45,  118,  137,  119,  119,  119,
       46,  180,  120,  121,  121,  121,   99,  122,  128,  128,
      181,  106,  129,  129,  129,  100,   43,  140,  122,  130,
      170,  170,  170,   99,  309,  127,  127,  131,  133,  132,

      132,  132,  100,   43,  312,  107,  107,   99,  106,   99,
       47,  106,   42,  106,   44,   45,  100,   43,  100,   43,
       99,   46,  110,  110,  110,  241,   99,  135,  139,  100,
       43,  138,  106,   99,  112,  100,   43,   99,  141,   99,
      136,   99,  100,   43,  300,   99,  100,   43,  100,   43,
      100,   43,  147,  142,  100,   43,  107,  107,   99,  106,
      143,  144,  106,   99,  145,  303,   99,  100,   43,  146,
      149,   99,  100,   43,  148,  100,   43,   99,  183,  294,
      100,   43,   99,  184,   99,  297,  100,   43,  150,  289,
       99,  100,   43,  100,   43,  279,   99,  285,  153,  100,

       43,   99,  286,  136,  151,  100,   43,   99,  260,  152,
      100,   43,   99,  154,  224,  155,  100,   43,   94,  247,
       99,  100,   43,   42,  136,   44,   45,   95,  156,  100,
      160,  171,   46,   99,  120,  158,  162,  172,  172,  163,
      163,  187,  159,  164,  164,  164,   42,  157,   44,   45,
      188,  180,   96,   96,  166,   46,  191,  167,  167,  194,
      181,  168,  168,  168,  103,  176,  176,   49,   49,  177,
      177,  177,  104,  175,  105,  105,  105,  368,  175,  368,
      368,  169,  159,  165,   94,  111,  368,  175,  187,  161,
      107,  107,  171,  182,  182,  182,  159,  188,  172,  172,

      173,  175,  105,  105,  105,  113,  174,  129,  129,  129,
      159,  196,  178,  111,   99,  102,   42,  174,   44,   45,
      198,  107,  107,  100,   43,   46,  110,  110,  110,  117,
      123,   94,  125,  126,   98,  368,   94,  118,  183,  119,
      119,  119,  202,  184,  120,   92,  185,   52,  119,  119,
      119,  281,  186,  189,  189,   51,  175,  190,  190,  190,
       99,  247,  368,  186,  368,  368,  195,  195,  195,  100,
       43,  283,  191,   56,  127,  127,  120,  321,   57,   58,
       58,  192,   60,  129,  129,  129,  130,  368,  205,  368,
      368,  196,  234,  368,  131,  368,  132,  132,  132,  197,

      198,  132,  132,  132,   99,  199,  127,  127,   99,  368,
       99,  368,   99,  100,   43,   99,  199,  100,   43,  100,
       43,  100,   43,  368,  100,   43,   99,  201,  368,  206,
       99,  203,   99,  204,  191,  100,   43,  208,   99,  100,
       43,  100,   43,  211,  207,   99,  368,  100,   43,  335,
      209,   99,  368,   99,  100,   43,  210,   99,  212,   99,
      100,   43,  100,   43,   99,  368,  100,   43,  100,   43,
      368,   99,  368,  100,   43,   99,  368,   99,  321,  368,
      100,   43,   99,  368,  100,   43,  100,   43,  213,  215,
       99,  100,   43,  234,  214,  164,  164,  164,  216,  100,

       43,  164,  164,  164,  368,  368,  217,  220,  219,   99,
      221,  221,   99,  368,  222,  222,  222,  223,  100,   43,
      218,  100,   43,  225,  225,  368,  368,  226,  226,  226,
      228,  228,  294,  368,  229,  229,  229,  168,  168,  168,
      168,  168,  168,  171,  177,  177,  177,  356,  231,  172,
      172,  368,  368,  170,  170,  170,  232,  174,  233,  233,
      233,  237,  237,  234,  171,  238,  238,  238,  174,  300,
      172,  172,  368,  239,  235,  235,  235,  368,  236,  177,
      177,  177,  175,  242,  358,  244,  245,  183,  368,  236,
      368,  159,  184,  252,  111,  254,  255,  182,  182,  182,

      368,  186,  250,  250,   99,  183,  251,  251,  251,  240,
      184,  368,  186,  100,   43,  248,  248,  248,  270,  249,
      190,  190,  190,  263,  368,  265,  266,  246,  246,  368,
      249,  222,  222,  222,   56,  368,  368,  256,  256,   57,
       58,   58,  368,   60,  190,  190,  190,  257,  196,  309,
      258,  258,  368,  368,  259,  259,  259,  198,  195,  195,
      195,   99,  199,  368,  360,  196,  368,  267,  267,  368,
      100,   43,  368,  199,  198,  261,  261,  261,   99,  262,
      268,  268,   99,  368,  269,  269,  269,  100,   43,   99,
      262,  100,   43,   99,  368,   99,  271,  368,  100,   43,

      272,   99,  100,   43,  100,   43,   99,  273,   99,  368,
      100,   43,  274,   99,  368,  100,   43,  100,   43,  368,
      368,   99,  100,   43,   99,  368,   99,  368,  368,  275,
      100,   43,   99,  100,   43,  100,   43,  276,   99,  368,
       99,  100,   43,  222,  222,  222,  368,  100,   43,  100,
       43,  277,  277,  368,  368,  278,  278,  278,  226,  226,
      226,  280,  229,  229,  229,  282,  231,  226,  226,  226,
      368,  229,  229,  229,  232,  368,  233,  233,  233,  368,
      285,  234,  284,  284,  284,  286,  368,  368,  287,  171,
      233,  233,  233,  368,  288,  172,  172,  368,  368,  235,

      235,  235,  368,  236,  368,  288,  290,  290,  368,  175,
      291,  291,  291,  171,  236,  238,  238,  238,  159,  172,
      172,  111,   99,  238,  238,  238,  368,  368,  368,  292,
      292,  100,   43,  293,  293,  293,  242,  368,  244,  245,
      368,  183,  368,  368,  368,  368,  184,  251,  251,  251,
      294,  248,  248,  248,  368,  249,  298,  298,  183,  295,
      299,  299,  299,  184,  368,  368,  249,  368,  251,  251,
      251,  252,  368,  254,  255,  368,  368,  368,  368,  368,
      246,  246,  368,  368,  246,  246,  300,  304,  304,  368,
      368,  305,  305,  305,  196,  301,  259,  259,  259,  259,

      259,  259,  368,  198,  261,  261,  261,  263,  262,  265,
      266,  269,  269,  269,  368,  256,  256,  368,  368,  262,
      256,  256,  307,  307,  196,  368,  308,  308,  308,  368,
      368,  368,  368,  198,  269,  269,  269,   99,  368,  309,
       99,  278,  278,  278,   99,  368,  100,   43,  310,  100,
       43,  267,  267,  100,   43,  313,   99,  368,   99,  368,
       99,  368,  368,  368,  368,  100,   43,  100,   43,  100,
       43,  315,  368,  267,  267,  314,  368,  278,  278,  278,
      317,  317,  368,  368,  318,  318,  318,  319,  319,  285,
      368,  320,  320,  320,  286,  368,  368,  285,  368,  284,

      284,  284,  286,  288,  291,  291,  291,  322,  322,  322,
      368,  323,  324,  324,  288,  368,  325,  325,  325,  171,
      368,  368,  323,  368,  368,  172,  172,  368,  368,  291,
      291,  291,  293,  293,  293,   47,  299,  299,  299,  368,
      368,  293,  293,  293,  326,  183,  368,  327,  327,  368,
      184,  328,  328,  328,   99,  299,  299,  299,  330,  368,
      368,  331,  331,  100,   43,  332,  332,  332,  305,  305,
      305,  334,  308,  308,  308,  196,  368,  305,  305,  305,
       99,  318,  318,  318,  198,  308,  308,  308,  336,  100,
       43,  337,  337,   94,  368,  338,  338,  338,  368,  318,

      318,  318,  175,  340,  320,  320,  320,  285,  320,  320,
      320,  368,  286,  325,  325,  325,  368,  322,  322,  322,
      368,  323,  341,  341,  285,  368,  342,  342,  342,  286,
       99,  368,  323,  368,  325,  325,  325,  343,  343,  100,
       43,  344,  344,  344,  328,  328,  328,  328,  328,  328,
      346,  346,  368,  368,  347,  347,  347,  332,  332,  332,
      332,  332,  332,  349,  349,  368,  368,  350,  350,  350,
      351,  351,  368,  368,  352,  352,  352,  338,  338,  338,
      338,  338,  338,   99,  342,  342,  342,  368,  368,  285,
      368,  368,  100,   43,  286,  368,  354,  368,  368,  342,

      342,  342,  344,  344,  344,  355,  347,  347,  347,  357,
      368,  344,  344,  344,  368,  347,  347,  347,  350,  350,
      350,  191,  352,  352,  352,  359,   99,  350,  350,  350,
      368,  352,  352,  352,  368,  100,   43,  368,  362,  362,
      368,  361,  363,  363,  363,  364,  364,  368,  368,  365,
      365,  365,  366,  366,  368,  368,  367,  367,  367,  363,
      363,  363,  294,  365,  365,  365,  300,  368,  363,  363,
      363,  368,  365,  365,  365,  367,  367,  367,  309,  368,
      368,  368,  368,  368,  367,  367,  367,   43,   43,   43,
      368,  368,   43,   43,  368,   43,   43,   43,   66,   66,

      368,  368,  368,  368,   66,   90,   90,   90,  368,  368,
       90,   90,  368,   90,  368,   90,   93,  368,  368,  368,
      368,   93,  368,   93,   93,   93,   96,  368,  368,  368,
      368,   96,  368,   96,  368,   96,  106,  106,  106,  368,
      368,  106,  368,  368,  106,  368,  106,  111,  111,  111,
      368,  368,  111,  368,  368,  111,  368,  111,  124,  124,
      124,  368,  368,  368,  368,  368,  124,  368,  124,  134,
      134,  134,  368,  134,  134,  134,  107,  368,  368,  368,
      368,  107,  368,  107,  368,  107,  179,  368,  368,  368,
      368,  368,  368,  179,  127,  368,  368,  368,  368,  127,

      368,  127,  368,  127,  200,  200,  368,  368,  200,  200,
      200,  227,  368,  368,  368,  368,  368,  368,  227,  230,
      368,  368,  368,  368,  368,  368,  230,  243,  243,  243,
      368,  368,  368,  368,  368,  243,  368,  243,  253,  253,
      253,  368,  368,  368,  368,  368,  253,  368,  253,  264,
      264,  264,  368,  368,  368,  368,  368,  264,  368,  264,
      246,  368,  368,  368,  368,  246,  368,  246,  368,  246,
      256,  368,  368,  368,  368,  256,  368,  256,  368,  256,
      306,  368,  368,  368,  368,  368,  368,  306,  267,  368,
      368,  368,  368,  267,  368,  267,  368,  267,  345,  368,

      368,  368,  368,  368,  368,  345,  348,  368,  368,  368,
      368,  368,  368,  348,  353,  368,  368,  368,  368,  368,
      368,  353,    5,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368
    } ;

static const flex_int16_t yy_chk[1779] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        7,    9,    7,    9,    9,   16,   23,   19,   23,   23,
        9,    9,   19,   16,   25,   16,   16,   16,   26,   27,
        9,   24,   24,   24,   23,   23,   57,   23,   28,   29,
       24,   25,   27,   27,   31,   24,   25,   30,   24,   26,
       28,   57,   30,   31,  396,    9,    9,   18,   29,   31,
       31,  393,   18,   18,   18,   18,   18,   18,   18,   18,
       35,   18,   32,   32,   41,   37,   41,  391,   34,  115,
       34,   34,   18,   20,   37,   20,   20,   34,   34,   42,
       43,  383,   20,   20,  115,  376,   46,   35,   42,   43,

       43,  374,   20,   20,   46,  370,   46,   46,   46,   37,
       37,   47,  312,   47,   47,   49,   63,   49,   49,   66,
       47,   63,   34,   34,   49,   49,   48,   20,   20,   48,
       48,   53,   66,   48,   48,   48,   67,  303,   55,   53,
       55,   55,   55,   56,  297,   67,   67,  289,   56,   56,
       56,   60,   56,   60,   60,   47,   47,   58,  279,   49,
       49,   50,   50,   50,   50,   58,   67,   58,   58,   58,
       50,  116,   58,   59,   59,   59,   70,   59,   62,   62,
      116,   50,   62,   62,   62,   70,   70,   70,   59,   64,
      104,  104,  104,   65,  267,   60,   60,   64,   65,   64,

       64,   64,   65,   65,  266,   50,   50,   68,   50,   69,
      179,   50,   51,   51,   51,   51,   68,   68,   69,   69,
       71,   51,  109,  109,  109,  179,   72,  134,   69,   71,
       71,   68,   51,   73,   51,   72,   72,   76,   72,   74,
      134,   75,   73,   73,  256,   78,   76,   76,   74,   74,
       75,   75,   76,   72,   78,   78,   51,   51,   77,   51,
       73,   74,   51,   79,   75,  255,   80,   77,   77,   75,
       78,   81,   79,   79,   77,   80,   80,   82,  183,  246,
       81,   81,   83,  183,   84,  245,   82,   82,   81,  234,
       85,   83,   83,   84,   84,  224,   86,  285,   84,   85,

       85,   87,  285,  200,   82,   86,   86,   88,  194,   83,
       87,   87,   89,   85,  161,   86,   88,   88,   93,  184,
       91,   89,   89,   90,  135,   90,   90,   93,   87,   91,
       91,  171,   90,   90,  184,   89,   95,  171,  171,   95,
       95,  120,   90,   95,   95,   95,   99,   88,   99,   99,
      120,  180,   93,   93,  100,   99,  127,  100,  100,  126,
      180,  100,  100,  100,  103,  108,  108,   90,   90,  108,
      108,  108,  103,  111,  103,  103,  103,  106,  107,  106,
      106,  102,  111,   98,   96,  111,  106,  106,  187,   92,
       99,   99,  105,  118,  118,  118,  106,  187,  105,  105,

      105,  112,  105,  105,  105,   52,  105,  128,  128,  128,
      112,  196,  112,  112,  138,   45,  110,  105,  110,  110,
      196,  106,  106,  138,  138,  110,  110,  110,  110,  117,
      123,   40,  123,  123,   39,  110,  227,  117,  119,  117,
      117,  117,  138,  119,  117,   36,  119,   11,  119,  119,
      119,  227,  119,  122,  122,   10,  230,  122,  122,  122,
      141,  247,  124,  119,  124,  124,  131,  131,  131,  141,
      141,  230,  124,  129,  123,  123,  247,  286,  129,  129,
      129,  124,  129,  129,  129,  129,  130,    5,  141,    0,
        0,  132,  286,    0,  130,    0,  130,  130,  130,  132,

      132,  132,  132,  132,  137,  132,  124,  124,  139,    0,
      140,    0,  142,  137,  137,  143,  132,  139,  139,  140,
      140,  142,  142,    0,  143,  143,  144,  137,    0,  142,
      145,  139,  147,  140,  306,  144,  144,  144,  146,  145,
      145,  147,  147,  147,  143,  148,    0,  146,  146,  306,
      145,  149,    0,  150,  148,  148,  146,  151,  148,  152,
      149,  149,  150,  150,  153,    0,  151,  151,  152,  152,
        0,  154,    0,  153,  153,  155,    0,  156,  321,    0,
      154,  154,  157,    0,  155,  155,  156,  156,  152,  154,
      158,  157,  157,  321,  153,  163,  163,  163,  155,  158,

      158,  164,  164,  164,    0,    0,  156,  159,  158,  205,
      159,  159,  160,    0,  159,  159,  159,  160,  205,  205,
      157,  160,  160,  162,  162,    0,    0,  162,  162,  162,
      166,  166,  345,    0,  166,  166,  166,  167,  167,  167,
      168,  168,  168,  170,  176,  176,  176,  345,  172,  170,
      170,    0,    0,  170,  170,  170,  172,  170,  172,  172,
      172,  174,  174,  172,  173,  174,  174,  174,  170,  348,
      173,  173,    0,  177,  173,  173,  173,    0,  173,  177,
      177,  177,  178,  181,  348,  181,  181,  182,    0,  173,
        0,  178,  182,  188,  178,  188,  188,  182,  182,  182,

        0,  182,  186,  186,  201,  185,  186,  186,  186,  178,
      185,    0,  182,  201,  201,  185,  185,  185,  201,  185,
      189,  189,  189,  198,    0,  198,  198,  181,  181,    0,
      185,  221,  221,  221,  190,    0,    0,  188,  188,  190,
      190,  190,    0,  190,  190,  190,  190,  192,  195,  353,
      192,  192,    0,    0,  192,  192,  192,  195,  195,  195,
      195,  206,  195,    0,  353,  197,    0,  198,  198,    0,
      206,  206,    0,  195,  197,  197,  197,  197,  202,  197,
      199,  199,  203,    0,  199,  199,  199,  202,  202,  204,
      197,  203,  203,  207,    0,  208,  202,    0,  204,  204,

      203,  209,  207,  207,  208,  208,  210,  204,  211,    0,
      209,  209,  208,  212,    0,  210,  210,  211,  211,    0,
        0,  213,  212,  212,  214,    0,  215,    0,    0,  211,
      213,  213,  216,  214,  214,  215,  215,  214,  217,    0,
      219,  216,  216,  222,  222,  222,    0,  217,  217,  219,
      219,  220,  220,    0,    0,  220,  220,  220,  225,  225,
      225,  226,  228,  228,  228,  229,  231,  226,  226,  226,
        0,  229,  229,  229,  231,    0,  231,  231,  231,    0,
      233,  231,  232,  232,  232,  233,    0,    0,  233,  235,
      233,  233,  233,    0,  233,  235,  235,    0,    0,  235,

      235,  235,    0,  235,    0,  233,  236,  236,    0,  240,
      236,  236,  236,  238,  235,  237,  237,  237,  240,  238,
      238,  240,  271,  238,  238,  238,  239,  239,  239,  241,
      241,  271,  271,  241,  241,  241,  242,    0,  242,  242,
      243,  248,  243,  243,    0,    0,  248,  250,  250,  250,
      243,  248,  248,  248,    0,  248,  249,  249,  251,  243,
      249,  249,  249,  251,    0,    0,  248,    0,  251,  251,
      251,  252,    0,  252,  252,    0,  253,    0,  253,  253,
      242,  242,    0,    0,  243,  243,  253,  257,  257,    0,
        0,  257,  257,  257,  261,  253,  258,  258,  258,  259,

      259,  259,    0,  261,  261,  261,  261,  263,  261,  263,
      263,  268,  268,  268,    0,  252,  252,    0,    0,  261,
      253,  253,  262,  262,  269,    0,  262,  262,  262,  264,
        0,  264,  264,  269,  269,  269,  269,  272,    0,  264,
      273,  277,  277,  277,  270,    0,  272,  272,  264,  273,
      273,  263,  263,  270,  270,  270,  274,    0,  275,    0,
      276,  282,  282,  282,    0,  274,  274,  275,  275,  276,
      276,  278,    0,  264,  264,  276,    0,  278,  278,  278,
      281,  281,    0,    0,  281,  281,  281,  283,  283,  284,
        0,  283,  283,  283,  284,    0,    0,  287,    0,  284,

      284,  284,  287,  284,  290,  290,  290,  287,  287,  287,
        0,  287,  288,  288,  284,    0,  288,  288,  288,  291,
        0,    0,  287,    0,    0,  291,  291,    0,    0,  291,
      291,  291,  292,  292,  292,  293,  298,  298,  298,    0,
        0,  293,  293,  293,  295,  299,    0,  295,  295,    0,
      299,  295,  295,  295,  314,  299,  299,  299,  301,    0,
        0,  301,  301,  314,  314,  301,  301,  301,  304,  304,
      304,  305,  307,  307,  307,  308,    0,  305,  305,  305,
      313,  317,  317,  317,  308,  308,  308,  308,  310,  313,
      313,  310,  310,  318,    0,  310,  310,  310,    0,  318,

      318,  318,  320,  313,  319,  319,  319,  322,  320,  320,
      320,    0,  322,  324,  324,  324,    0,  322,  322,  322,
        0,  322,  323,  323,  325,    0,  323,  323,  323,  325,
      361,    0,  322,    0,  325,  325,  325,  326,  326,  361,
      361,  326,  326,  326,  327,  327,  327,  328,  328,  328,
      330,  330,    0,    0,  330,  330,  330,  331,  331,  331,
      332,  332,  332,  335,  335,    0,    0,  335,  335,  335,
      336,  336,    0,    0,  336,  336,  336,  337,  337,  337,
      338,  338,  338,  340,  341,  341,  341,    0,    0,  342,
        0,    0,  340,  340,  342,    0,  340,    0,    0,  342,

      342,  342,  343,  343,  343,  344,  346,  346,  346,  347,
        0,  344,  344,  344,    0,  347,  347,  347,  349,  349,
      349,  350,  351,  351,  351,  352,  354,  350,  350,  350,
        0,  352,  352,  352,    0,  354,  354,    0,  356,  356,
        0,  354,  356,  356,  356,  358,  358,    0,    0,  358,
      358,  358,  360,  360,    0,    0,  360,  360,  360,  362,
      362,  362,  363,  364,  364,  364,  365,    0,  363,  363,
      363,    0,  365,  365,  365,  366,  366,  366,  367,    0,
        0,    0,    0,    0,  367,  367,  367,  369,  369,  369,
        0,    0,  369,  369,    0,  369,  369,  369,  371,  371,

        0,    0,    0,    0,  371,  372,  372,  372,    0,    0,
      372,  372,    0,  372,    0,  372,  373,    0,    0,    0,
        0,  373,    0,  373,  373,  373,  375,    0,    0,    0,
        0,  375,    0,  375,    0,  375,  377,  377,  377,    0,
        0,  377,    0,    0,  377,    0,  377,  378,  378,  378,
        0,    0,  378,    0,    0,  378,    0,  378,  379,  379,
      379,    0,    0,    0,    0,    0,  379,    0,  379,  380,
      380,  380,    0,  380,  380,  380,  381,    0,    0,    0,
        0,  381,    0,  381,    0,  381,  382,    0,    0,    0,
        0,    0,    0,  382,  384,    0,    0,    0,    0,  384,

        0,  384,    0,  384,  385,  385,    0,    0,  385,  385,
      385,  386,    0,    0,    0,    0,    0,    0,  386,  387,
        0,    0,    0,    0,    0,    0,  387,  388,  388,  388,
        0,    0,    0,    0,    0,  388,    0,  388,  389,  389,
      389,    0,    0,    0,    0,    0,  389,    0,  389,  390,
      390,  390,    0,    0,    0,    0,    0,  390,    0,  390,
      392,    0,    0,    0,    0,  392,    0,  392,    0,  392,
      394,    0,    0,    0,    0,  394,    0,  394,    0,  394,
      395,    0,    0,    0,    0,    0,    0,  395,  397,    0,
        0,    0,    0,  397,    0,  397,    0,  397,  398,    0,

        0,    0,    0,    0,    0,  398,  399,    0,    0,    0,
        0,    0,    0,  399,  400,    0,    0,    0,    0,    0,
        0,  400,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/SIScalarScanner.l"
#define YY_NO_INPUT 1
#line 6 "src/SIScalarScanner.l"
    extern  void siserror(char *s, ...);
    #include "SILibrary.h"
    #include "SIScalarParser.h"
    #include "SIScalar.tab.h"
    static double complex temp;
    extern OCStringRef scalarError;  // forward declare parser's error string
#line 1230 "src/SIScalarScanner.c"

/* exponent */
/* unit can be constant starting with &
 unit can be constant ending with 0
 unit can be symbol raised to arbitrary power.
 */
#line 1237 "src/SIScalarScanner.c"

#define INITIAL 0
#define together 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 42 "src/SIScalarScanner.l"

#line 1455 "src/SIScalarScanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1723 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
#line 44 "src/SIScalarScanner.l"
case 2:
#line 45 "src/SIScalarScanner.l"
case 3:
#line 46 "src/SIScalarScanner.l"
case 4:
#line 47 "src/SIScalarScanner.l"
case 5:
#line 48 "src/SIScalarScanner.l"
case 6:
#line 49 "src/SIScalarScanner.l"
case 7:
#line 50 "src/SIScalarScanner.l"
case 8:
YY_RULE_SETUP
#line 50 "src/SIScalarScanner.l"
{return yytext[0];}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "src/SIScalarScanner.l"
{sislval.math_fn = BM_acos; return MATH_FUNC;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "src/SIScalarScanner.l"
{sislval.math_fn = BM_acosh; return MATH_FUNC;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "src/SIScalarScanner.l"
{sislval.math_fn = BM_asin; return MATH_FUNC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "src/SIScalarScanner.l"
{sislval.math_fn = BM_asinh; return MATH_FUNC;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "src/SIScalarScanner.l"
{sislval.math_fn = BM_atan; return MATH_FUNC;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "src/SIScalarScanner.l"
{sislval.math_fn = BM_atanh; return MATH_FUNC;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cos; return MATH_FUNC;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cosh; return MATH_FUNC;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sin; return MATH_FUNC;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sinh; return MATH_FUNC;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "src/SIScalarScanner.l"
{sislval.math_fn = BM_tan; return MATH_FUNC;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "src/SIScalarScanner.l"
{sislval.math_fn = BM_tanh; return MATH_FUNC;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "src/SIScalarScanner.l"
{sislval.math_fn = BM_erf; return MATH_FUNC;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "src/SIScalarScanner.l"
{sislval.math_fn = BM_erfc; return MATH_FUNC;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "src/SIScalarScanner.l"
{sislval.math_fn = BM_exp; return MATH_FUNC;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "src/SIScalarScanner.l"
{sislval.math_fn = BM_ln; return MATH_FUNC;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "src/SIScalarScanner.l"
{sislval.math_fn = BM_log; return MATH_FUNC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "src/SIScalarScanner.l"
{sislval.math_fn = BM_conj; return MATH_FUNC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "src/SIScalarScanner.l"
{sislval.math_fn = BM_creal; return MATH_FUNC;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cimag; return MATH_FUNC;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "src/SIScalarScanner.l"
{sislval.math_fn = BM_carg; return MATH_FUNC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cabs; return MATH_FUNC;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "src/SIScalarScanner.l"
{sislval.math_fn = BM_sqrt; return MATH_FUNC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "src/SIScalarScanner.l"
{sislval.math_fn = BM_cbrt; return MATH_FUNC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "src/SIScalarScanner.l"
{sislval.math_fn = BM_qtrt; return MATH_FUNC;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 78 "src/SIScalarScanner.l"
{sislval.math_fn = BM_reduce; return MATH_FUNC;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "src/SIScalarScanner.l"
{sislval.const_fn = BC_AW; return CONST_FUNC;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "src/SIScalarScanner.l"
{sislval.const_fn = BC_FW; return CONST_FUNC;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Abundance; return CONST_FUNC;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Gyromag; return CONST_FUNC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_MagneticDipole; return CONST_FUNC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_ElectricQuadrupole; return CONST_FUNC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "src/SIScalarScanner.l"
{sislval.const_fn = BC_nmr; return CONST_FUNC;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_Spin; return CONST_FUNC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "src/SIScalarScanner.l"
{sislval.const_fn = BC_Isotope_HalfLife; return CONST_FUNC;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "src/SIScalarScanner.l"
{double multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(STR("ℏ"),&multiplier, &scalarError);
    sislval.d = SIScalarCreateWithDouble(multiplier,unit);
    return SCALAR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    sislval.d = SIScalarCreateWithDoubleComplex(temp, NULL);
    return SCALAR;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "src/SIScalarScanner.l"
{
    OCStringRef string = OCStringCreateWithCString(yytext);
    double unit_multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(string, &unit_multiplier, &scalarError);
    if(unit == NULL) {
        if(string) OCRelease(string);
        yyterminate();
        }
    sislval.d = SIScalarCreateWithDouble(unit_multiplier, unit);
    OCRelease(string);
    return SCALAR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 153 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 163 "src/SIScalarScanner.l"
{
    temp = OCComplexFromCString(yytext);
    BEGIN(together);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 168 "src/SIScalarScanner.l"
{
    OCStringRef string = OCStringCreateWithCString(yytext);
    double unit_multiplier = 1;
    SIUnitRef unit = SIUnitForSymbol(string, &unit_multiplier,&scalarError);
    if(unit==NULL) {
        if(string) OCRelease(string);
        yyterminate();
        BEGIN(INITIAL);
        return SCALAR;
    }
    sislval.d = SIScalarCreateWithDoubleComplex(temp*unit_multiplier, unit);
    OCRelease(string);
    BEGIN(INITIAL);
    return SCALAR;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 183 "src/SIScalarScanner.l"
{
    sislval.const_string = OCMutableStringCreateWithCString(yytext);
    return CONST_STRING;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 187 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 191 "src/SIScalarScanner.l"
{
    sislval.d = NULL;
    return SCALAR;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 195 "src/SIScalarScanner.l"
{/* ignore whitespace */}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 196 "src/SIScalarScanner.l"
{return(yytext[0]);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 198 "src/SIScalarScanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1881 "src/SIScalarScanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(together):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 368);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 198 "src/SIScalarScanner.l"


